import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const C={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, content-type, apikey, x-client-info','access-control-allow-methods':'GET,POST,OPTIONS','content-type':'application/json; charset=utf-8'};
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});const E=new TextEncoder();const H=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',E.encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');const DB=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});async function body(r:Request){try{return await r.json()}catch{return {}}}async function auth(r:Request){const raw=(r.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!raw)return null;const {data:s}=await DB().from('sns_sessions').select('account_id,expires_at').eq('token_hash',await H(raw)).maybeSingle();if(!s||Date.parse(s.expires_at)<=Date.now())return null;return {id:s.account_id}}
const code=()=>{const b=crypto.getRandomValues(new Uint8Array(9));return 'ROOM-'+Array.from(b,x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()};
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('',{status:204,headers:C});const u=new URL(r.url),route=u.pathname.replace(/^.*\/shinobi-rooms/,'')||'/';try{if(route==='/'||route==='/health')return J({ok:true,service:'shinobi-rooms',version:'R39',pcRequired:false});const a=await auth(r);if(!a)return J({ok:false,error:'Sessão inválida.'},401);const db=DB(),b=r.method==='POST'?await body(r):{};
 if(route==='/create'&&r.method==='POST'){const roomCode=code(),title=String(b.title||'Campanha Online').slice(0,100),campaignId=String(b.campaignId||''),state={title,campaignId,createdBy:a.id};const {error}=await db.from('sns_rooms').insert({code:roomCode,owner_account_id:a.id,state,revision:1});if(error)throw error;await db.from('sns_room_members').upsert({room_code:roomCode,account_id:a.id,character:b.character||{},last_seen_at:new Date().toISOString()},{onConflict:'room_code,account_id'});return J({ok:true,roomId:roomCode,title,campaignId});}
 const roomCode=String(b.roomId||u.searchParams.get('roomId')||'').trim().toUpperCase();if(!roomCode)return J({ok:false,error:'roomId obrigatório.'},400);const {data:room}=await db.from('sns_rooms').select('code,state,revision,updated_at').eq('code',roomCode).maybeSingle();if(!room)return J({ok:false,error:'Sala não encontrada.'},404);
 if(route==='/join'&&r.method==='POST'){await db.from('sns_room_members').upsert({room_code:roomCode,account_id:a.id,character:b.character||{},last_seen_at:new Date().toISOString()},{onConflict:'room_code,account_id'});return J({ok:true,roomId:roomCode,title:room.state?.title||'Campanha Online',campaignId:room.state?.campaignId||b.campaignId||''});}
 const {data:membership}=await db.from('sns_room_members').select('account_id').eq('room_code',roomCode).eq('account_id',a.id).maybeSingle();if(!membership)return J({ok:false,error:'Entre na sala antes de acessar este recurso.'},403);
 if(route==='/heartbeat'&&r.method==='POST'){await db.from('sns_room_members').update({character:b.character||{},last_seen_at:new Date().toISOString()}).eq('room_code',roomCode).eq('account_id',a.id);return J({ok:true});}
 if(route==='/room'){const cutoff=new Date(Date.now()-180000).toISOString();const {data:members}=await db.from('sns_room_members').select('account_id,character,last_seen_at,joined_at').eq('room_code',roomCode).gte('last_seen_at',cutoff).order('joined_at');return J({ok:true,room:{roomId:room.code,title:room.state?.title||'Campanha Online',campaignId:room.state?.campaignId||'',revision:room.revision,members:members||[]}});}
 if(route==='/message'&&r.method==='POST'){const msg=String(b.message||'').trim().slice(0,1500);if(!msg)return J({ok:false,error:'Mensagem vazia.'},400);const {data,error}=await db.from('sns_room_messages').insert({room_code:roomCode,account_id:a.id,character_name:String(b.characterName||'Shinobi').slice(0,80),message:msg}).select('id,character_name,message,created_at').single();if(error)throw error;return J({ok:true,message:data});}
 if(route==='/messages'){const after=Math.max(0,Number(b.afterId||u.searchParams.get('afterId')||0));const {data,error}=await db.from('sns_room_messages').select('id,character_name,message,created_at').eq('room_code',roomCode).gt('id',after).order('id').limit(100);if(error)throw error;return J({ok:true,messages:(data||[]).map((x:any)=>({id:x.id,characterName:x.character_name,message:x.message,at:x.created_at}))});}
 return J({ok:false,error:'Rota não encontrada.'},404)}catch(e:any){console.error(e);return J({ok:false,error:e?.message||'Falha nas salas online.'},500)}});
