import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
const BODY_MAX=16*1024;
const C={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"GET,POST,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String(o.default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const admin=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});
class AppError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
async function requireUser(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new AppError(401,"AUTH","Sessão de recuperação inválida ou expirada.");const c=createClient(URL,PUB,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new AppError(401,"AUTH","Sessão de recuperação inválida ou expirada.");return data.user}
function route(req:Request){const p=new URL(req.url).pathname;return p.replace(/^.*\/legacy-account-recovery/,"")||"/"}
async function readBody(req:Request){const declared=Number(req.headers.get("content-length")||"0");if(Number.isFinite(declared)&&declared>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");const raw=await req.arrayBuffer();if(raw.byteLength>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");if(!raw.byteLength)return{} as Record<string,any>;try{const v=JSON.parse(new TextDecoder().decode(raw));if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v as Record<string,any>}catch{throw new AppError(400,"INVALID_JSON","JSON inválido.")}}
const b64=(u:Uint8Array)=>btoa(String.fromCharCode(...u));
async function hashPassword(password:string,salt:Uint8Array,iterations=120000){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-1",salt,iterations},key,256);return b64(new Uint8Array(bits))}
async function rateLimit(db:any,userId:string){const now=new Date(),since=new Date(now.getTime()-10*60_000).toISOString();const {error:ie}=await db.from("legacy_recovery_rate_events").insert({user_id:userId});if(ie)throw ie;const {count,error}=await db.from("legacy_recovery_rate_events").select("id",{head:true,count:"exact"}).eq("user_id",userId).gte("created_at",since);if(error)throw error;if(Number(count||0)>5)throw new AppError(429,"RECOVERY_RATE_LIMIT","Muitas sincronizações de senha. Aguarde 10 minutos.")}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});try{const r=route(req);if(!["GET","POST"].includes(req.method))return J({ok:false,code:"METHOD",error:"Método inválido."},405);const u=await requireUser(req),db=admin();
  if(r==="/status"){if(req.method!=="GET")return J({ok:false,code:"METHOD",error:"Método inválido."},405);const {data,error}=await db.from("naruto_accounts").select("id,user_name,recovery_verified").eq("auth_user_id",u.id).maybeSingle();if(error)throw error;return J({ok:true,linked:!!data,recoveryReady:!!data?.recovery_verified,username:data?.user_name||null})}
  if(r==="/sync-password"){if(req.method!=="POST")return J({ok:false,code:"METHOD",error:"Método inválido."},405);const b=await readBody(req),password=String(b.password||"");if(password.length<8||password.length>128)throw new AppError(400,"PASSWORD_POLICY","A senha deve ter entre 8 e 128 caracteres.");const {data:account,error}=await db.from("naruto_accounts").select("id,user_name,auth_user_id,recovery_verified").eq("auth_user_id",u.id).maybeSingle();if(error)throw error;if(!account)throw new AppError(404,"LEGACY_LINK","Nenhuma conta de jogo está vinculada a esta identidade.");if(!account.recovery_verified)throw new AppError(403,"RECOVERY_NOT_VERIFIED","A recuperação desta conta ainda não foi ativada.");await rateLimit(db,u.id);const salt=crypto.getRandomValues(new Uint8Array(16)),iterations=120000,pass_hash=await hashPassword(password,salt,iterations);const {error:updateError}=await db.from("naruto_accounts").update({kdf:"pbkdf2-sha1",iterations,salt:b64(salt),pass_hash,session_token:null}).eq("id",account.id).eq("auth_user_id",u.id);if(updateError)throw updateError;return J({ok:true,username:account.user_name,message:"Senha da conta de jogo atualizada. Faça login novamente."})}
  return J({ok:false,code:"ROUTE",error:"Rota de recuperação desconhecida."},404)
}catch(e:any){if(e instanceof AppError)return J({ok:false,code:e.code,error:e.message},e.status);console.error("legacy-account-recovery",e);return J({ok:false,code:"RECOVERY",error:"Falha interna na recuperação."},503)}});
