import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { baseChakra,type RankedState,type Fighter } from "../_shared/ranked-engine.ts";
import { normalizeRaidActions,validateRaidTechniques,applyRaidItem,resolveRaidTechniquePhase } from "../_shared/raid-engine.ts";

const URL=Deno.env.get("SUPABASE_URL")!;
const BODY_MAX=128*1024,ID_MAX=120;
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const STARTERS=new Set(["naruto-uzumaki","sasuke-uchiha","sakura-haruno"]);
const C={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"GET,POST,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String(o.default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});
class AppError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
const admin=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
async function user(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new AppError(401,"AUTH","Sessão inválida.");const c=createClient(URL,PUB,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new AppError(401,"AUTH","Sessão inválida.");return data.user}
async function body(req:Request){const declared=Number(req.headers.get("content-length")||"0");if(Number.isFinite(declared)&&declared>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");const raw=await req.arrayBuffer();if(raw.byteLength>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");if(!raw.byteLength)return{} as Record<string,any>;try{const v=JSON.parse(new TextDecoder().decode(raw));if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v as Record<string,any>}catch{throw new AppError(400,"INVALID_JSON","JSON inválido.")}}
function route(req:Request){const p=new URL(req.url).pathname;return p.replace(/^.*\/events/,"")||"/"}
function uuid(v:unknown,code:string){const s=String(v||"");if(!UUID_RE.test(s))throw new AppError(400,code,"Identificador inválido.");return s}
function textId(v:unknown,label:string){const s=String(v||"").trim();if(!s||s.length>ID_MAX||/[\u0000-\u001f\u007f]/.test(s))throw new AppError(400,"INPUT",`${label} inválido.`);return s}
function teamIds(raw:any){if(!Array.isArray(raw)||raw.length<1||raw.length>3)throw new AppError(400,"TEAM","Equipe deve ter 1 a 3 personagens.");const ids=raw.map((x:any)=>String(typeof x==="string"?x:x?.characterId||x?.id||"").trim());if(ids.some(x=>!x||x.length>ID_MAX)||new Set(ids).size!==ids.length)throw new AppError(400,"TEAM","Equipe contém personagem inválido ou duplicado.");return ids}
function mapDb(e:any){const m=String(e?.message||"").toLowerCase();if(m.includes("insufficient item"))return new AppError(409,"RAID_ITEM_QTY","Quantidade de item insuficiente.");if(m.includes("raid attempt not found"))return new AppError(404,"ATTEMPT","Tentativa ausente.");if(m.includes("raid not won"))return new AppError(409,"RAID_NOT_WON","A raid ainda não foi vencida.");return null}

Deno.serve(async req=>{
  if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});
  try{
    const r=route(req);
    if(r==="/active"){
      if(req.method!=="GET")return J({ok:false,code:"METHOD",error:"Método inválido."},405);
      await user(req);return active(admin());
    }
    if(req.method!=="POST")return J({ok:false,code:"METHOD",error:"Método inválido."},405);
    const u=await user(req),db=admin(),b=await body(req);
    if(r==="/enter")return enter(db,u.id,b);
    if(r==="/raid/start")return startRaid(db,u.id,b);
    if(r==="/raid/turn")return raidTurn(db,u.id,b);
    if(r==="/raid/finish")return J({ok:false,code:"RAID_PROTOCOL",error:"A Raid R37 é autoritativa. Use /events/raid/turn; o cliente não pode declarar vitória."},410);
    return J({ok:false,code:"ROUTE",error:"Rota desconhecida."},404);
  }catch(e:any){if(e instanceof AppError)return J({ok:false,code:e.code,error:e.message},e.status);const status=Number(e?.status||0);if(status>=400&&status<500)return J({ok:false,code:"EVENT_INPUT",error:String(e?.message||"Ação inválida.")},status);const mapped=mapDb(e);if(mapped)return J({ok:false,code:mapped.code,error:mapped.message},mapped.status);console.error("events",e);return J({ok:false,code:"EVENT_API",error:"Falha interna nos eventos."},503)}
});

async function active(db:any){const now=new Date().toISOString(),{data,error}=await db.from("event_instances").select("*").lte("starts_at",now).gte("ends_at",now).in("status",["SCHEDULED","ACTIVE"]).order("starts_at");if(error)throw error;return J({ok:true,events:data||[]})}
async function enter(db:any,userId:string,b:any){const eventId=uuid(b.eventId,"EVENT"),{data:e,error}=await db.from("event_instances").select("*").eq("id",eventId).maybeSingle();if(error)throw error;if(!e)throw new AppError(404,"EVENT","Evento ausente.");const now=Date.now();if(e.status==="ENDED"||now<Date.parse(e.starts_at)||now>Date.parse(e.ends_at))throw new AppError(409,"EVENT_WINDOW","Evento fora da janela ativa.");const {error:pe}=await db.from("event_progress").upsert({user_id:userId,event_id:e.id,progress:{enteredAt:new Date().toISOString()}},{onConflict:"user_id,event_id"});if(pe)throw pe;return J({ok:true,event:e})}
async function startRaid(db:any,userId:string,b:any){const eventId=uuid(b.eventId,"EVENT"),{data:e,error}=await db.from("event_instances").select("*").eq("id",eventId).maybeSingle();if(error)throw error;if(!e)throw new AppError(404,"EVENT","Evento ausente.");if(!e.boss_id)throw new AppError(400,"RAID","Evento sem boss.");const now=Date.now();if(e.status==="ENDED"||now<Date.parse(e.starts_at)||now>Date.parse(e.ends_at))throw new AppError(409,"RAID_WINDOW","Evento fora da janela ativa.");const {data:existing,error:xe}=await db.from("raid_attempts").select("*").eq("user_id",userId).eq("event_id",e.id).eq("status","ACTIVE").order("created_at",{ascending:false}).limit(1).maybeSingle();if(xe)throw xe;if(existing){const boss=await bossMeta(db,existing.boss_id);return J({ok:true,existing:true,attemptId:existing.id,event:{id:e.id,name:e.name,cycle:e.cycle,bossId:e.boss_id},boss,sceneId:boss?.sceneId||null,battle:publicRaid(existing)})}
  const ids=teamIds(b.team),you=await buildPlayerTeam(db,userId,ids),boss=await buildBossTeam(db,textId(e.boss_id,"bossId")),state:RankedState={turn:1,players:{a:userId,b:`raid:${e.boss_id}`},teams:{a:you,b:boss.team},chakra:{a:baseChakra(),b:baseChakra()},events:[],resolvedSubmissions:{}};
  const {data:a,error:ae}=await db.from("raid_attempts").insert({user_id:userId,event_id:e.id,boss_id:e.boss_id,state,turn:1,status:"ACTIVE"}).select("*").single();if(ae){if(String(ae.code)==="23505"){const {data:race,error:re}=await db.from("raid_attempts").select("*").eq("user_id",userId).eq("event_id",e.id).eq("status","ACTIVE").limit(1).maybeSingle();if(re)throw re;if(race)return J({ok:true,existing:true,attemptId:race.id,event:{id:e.id,name:e.name,cycle:e.cycle,bossId:e.boss_id},boss:boss.boss,sceneId:boss.boss.sceneId||null,battle:publicRaid(race)})}throw ae}return J({ok:true,existing:false,attemptId:a.id,event:{id:e.id,name:e.name,cycle:e.cycle,bossId:e.boss_id},boss:boss.boss,sceneId:boss.boss.sceneId||null,battle:publicRaid(a)})}
async function raidTurn(db:any,userId:string,b:any){const id=uuid(b.attemptId,"ATTEMPT"),turn=Number(b.turn),sid=uuid(b.submissionId,"SUBMISSION");if(!Number.isInteger(turn)||turn<1||turn>10000)throw new AppError(400,"RAID_TURN","Turno inválido.");const {data:a,error}=await db.from("raid_attempts").select("*").eq("id",id).eq("user_id",userId).maybeSingle();if(error)throw error;if(!a)throw new AppError(404,"ATTEMPT","Tentativa ausente.");if(a.status!=="ACTIVE")return J({ok:true,duplicate:true,battle:publicRaid(a),reward:a.winner==="you"?await safeRaidReward(db,userId,id):null});if(Number(a.turn)!==turn)throw new AppError(409,"TURN_MISMATCH",`Turno esperado ${a.turn}.`);let actions;try{actions=normalizeRaidActions(b.actions)}catch(e:any){throw new AppError(Number(e?.status||400),"ACTIONS",String(e?.message||"Ação inválida."))}for(const x of actions){if(x.techniqueId)textId(x.techniqueId,"techniqueId");if(x.itemId)textId(x.itemId,"itemId")}const state=structuredClone(a.state) as RankedState;try{validateRaidTechniques(state,actions)}catch(e:any){throw new AppError(Number(e?.status||400),"ACTIONS",String(e?.message||"Ação inválida."))}
  const itemActions=actions.filter(x=>x.type==="item"),counts:Record<string,number>={},itemEvents:any[]=[];
  if(itemActions.length){const ids=[...new Set(itemActions.map(x=>x.itemId!))],{data:defs,error:de}=await db.from("content_entities").select("entity_id,published").eq("entity_type","item").in("entity_id",ids).not("published","is",null);if(de)throw de;const map=new Map((defs||[]).map((x:any)=>[x.entity_id,x.published])),{data:owned,error:oe}=await db.from("player_items").select("item_id,qty").eq("user_id",userId).in("item_id",ids);if(oe)throw oe;const qty=new Map((owned||[]).map((x:any)=>[x.item_id,Number(x.qty||0)]));for(const action of itemActions){const item:any=map.get(action.itemId!);if(!item||!item.allowedModes?.includes("raid"))throw new AppError(400,"RAID_ITEM",`Item não permitido: ${action.itemId}`);counts[action.itemId!]=(counts[action.itemId!]||0)+1;if((qty.get(action.itemId!)||0)<counts[action.itemId!])throw new AppError(409,"RAID_ITEM_QTY","Quantidade de item insuficiente.");itemEvents.push(applyRaidItem(state,action,item))}}
  const resolution=resolveRaidTechniquePhase(state,actions,`${id}:${a.boss_id}`);resolution.events=[...itemEvents,...(resolution.events||[])];const winner=resolution.winnerSide==="a"?"you":resolution.winnerSide==="b"?"boss":null,status=winner?"ENDED":"ACTIVE",result=winner?{ok:winner==="you",winner,metrics:{turns:turn},serverResolved:true}:null,{data:commit,error:ce}=await db.rpc("commit_raid_turn",{p_user_id:userId,p_attempt_id:id,p_expected_turn:turn,p_submission_id:sid,p_actions:actions,p_new_state:state,p_status:status,p_winner:winner,p_result:result,p_item_counts:counts});if(ce){const mapped=mapDb(ce);if(mapped)throw mapped;throw ce}const latest=await loadAttempt(db,userId,id),reward=winner==="you"?await safeRaidReward(db,userId,id):null;return J({ok:true,duplicate:!!commit?.duplicate,resolution,battle:publicRaid(latest),reward,event:await eventView(db,latest.event_id),kind:reward?.kind||null,account:await raidAccountView(db,userId)})}
async function raidAccountView(db:any,userId:string){const [p,items,gear,unlocks]=await Promise.all([db.from("profiles").select("ryo,xp,level").eq("user_id",userId).single(),db.from("player_items").select("item_id,qty").eq("user_id",userId),db.from("player_equipment").select("equipment_id,owned,durability").eq("user_id",userId),db.from("player_unlocks").select("entity_id").eq("user_id",userId).eq("entity_type","character")]);for(const x of [p,items,gear,unlocks])if(x.error)throw x.error;return{ryo:Number(p.data?.ryo||0),xp:Number(p.data?.xp||0),level:Number(p.data?.level||1),items:Object.fromEntries((items.data||[]).filter((x:any)=>Number(x.qty)>0).map((x:any)=>[x.item_id,Number(x.qty)])),equipment:Object.fromEntries((gear.data||[]).map((x:any)=>[x.equipment_id,{owned:!!x.owned,durability:Number(x.durability||0)}])),unlockedCharacters:(unlocks.data||[]).map((x:any)=>x.entity_id)}}
async function safeRaidReward(db:any,userId:string,id:string){const {data,error}=await db.rpc("claim_raid_completion",{p_user_id:userId,p_attempt_id:id});if(error){const mapped=mapDb(error);if(mapped)throw mapped;throw error}return data}
async function loadAttempt(db:any,userId:string,id:string){const {data,error}=await db.from("raid_attempts").select("*").eq("id",id).eq("user_id",userId).single();if(error)throw error;return data}
async function eventView(db:any,id:string){const {data,error}=await db.from("event_instances").select("id,name,cycle,boss_id").eq("id",id).maybeSingle();if(error)throw error;return data||null}
async function bossMeta(db:any,bossId:string){const {data,error}=await db.from("content_entities").select("published").eq("entity_type","boss").eq("entity_id",bossId).maybeSingle();if(error)throw error;return data?.published||null}
function publicRaid(a:any){const s=a.state as RankedState;return{id:a.id,status:a.status,turn:a.turn,winner:a.winner,you:s?.teams?.a||[],ai:s?.teams?.b||[],chakra:{you:s?.chakra?.a||baseChakra(),ai:s?.chakra?.b||baseChakra()},events:s?.events||[]}}
async function buildPlayerTeam(db:any,userId:string,ids:string[]):Promise<Fighter[]>{const {data:unlocks,error:ue}=await db.from("player_unlocks").select("entity_id").eq("user_id",userId).eq("entity_type","character").in("entity_id",ids);if(ue)throw ue;const allowed=new Set([...STARTERS,...(unlocks||[]).map((x:any)=>String(x.entity_id))]);for(const id of ids)if(!allowed.has(id))throw new AppError(403,"CHARACTER_LOCKED",`Personagem bloqueado: ${id}`);return buildTeam(db,userId,ids,true)}
async function buildBossTeam(db:any,bossId:string){const {data:be,error}=await db.from("content_entities").select("published").eq("entity_type","boss").eq("entity_id",bossId).maybeSingle();if(error)throw error;const boss=be?.published;if(!boss)throw new AppError(400,"BOSS",`Boss não publicado: ${bossId}`);const ids=boss.characterId?[String(boss.characterId)]:[];if(!ids.length)throw new AppError(400,"BOSS","Boss sem personagem de combate.");const team=await buildTeam(db,"",ids,false);if(team[0]){team[0].hp=team[0].maxHp=Math.max(1,Math.min(1000000,Number(boss.hp||team[0].maxHp)));if(boss.techniqueIds?.length){const techniqueIds=(boss.techniqueIds as any[]).map(String).filter((x:string)=>x&&x.length<=ID_MAX).slice(0,16),{data:te,error}=await db.from("content_entities").select("entity_id,published").eq("entity_type","technique").in("entity_id",techniqueIds).not("published","is",null);if(error)throw error;const m=new Map((te||[]).map((x:any)=>[x.entity_id,x.published]));team[0].skills=techniqueIds.map((id:string)=>m.get(id)).filter(Boolean).slice(0,4)}}return{boss,team}}
async function buildTeam(db:any,userId:string,ids:string[],useLoadout:boolean):Promise<Fighter[]>{const {data:chars,error}=await db.from("content_entities").select("entity_id,published").eq("entity_type","character").in("entity_id",ids).not("published","is",null);if(error)throw error;const cm=new Map((chars||[]).map((x:any)=>[x.entity_id,x.published]));let slots:any[]=[];if(useLoadout){const r=await db.from("player_loadout_slots").select("character_id,slot,technique_id").eq("user_id",userId).in("character_id",ids);if(r.error)throw r.error;slots=r.data||[]}const by=new Map<string,any[]>();for(const s of slots){const a=by.get(s.character_id)||[];a.push(s);by.set(s.character_id,a)}const techIds=new Set<string>();for(const id of ids){const c:any=cm.get(id);if(!c)throw new AppError(400,"CHARACTER",`Personagem não publicado: ${id}`);const ls=(by.get(id)||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.technique_id).filter(Boolean),base=(ls.length?ls:c.baseTechniqueIds||[]).slice(0,4);for(const t of base)techIds.add(String(t))}const {data:tech,error:te}=techIds.size?await db.from("content_entities").select("entity_id,published").eq("entity_type","technique").in("entity_id",[...techIds]).not("published","is",null):{data:[],error:null};if(te)throw te;const tm=new Map((tech||[]).map((x:any)=>[x.entity_id,x.published]));return ids.map(id=>{const c:any=cm.get(id),ls=(by.get(id)||[]).sort((a,b)=>a.slot-b.slot).map(x=>x.technique_id).filter(Boolean),skillIds=(ls.length?ls:c.baseTechniqueIds||[]).slice(0,4),hp=Math.max(1,Math.min(100000,Number(c.hp||100))),skills=skillIds.map((x:string)=>tm.get(String(x))).filter(Boolean);if(!skills.length)throw new AppError(400,"LOADOUT",`Loadout sem técnica publicada: ${id}`);return{characterId:id,name:String(c.name||id).slice(0,120),hp,maxHp:hp,shield:0,statuses:[],cooldowns:{},skills,stats:c.stats||{}}})}
