import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
const BODY_MAX=8*1024, TOKEN_RE=/^[a-f0-9]{32}$/i, PASSWORD_MAX=256;
const ALLOWED=new Set(["https://kaalflash12.github.io","http://localhost:8000","http://127.0.0.1:8000"]);
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String(o.default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const admin=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const authClient=()=>createClient(URL,PUB,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
class AppError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
function headers(req:Request){const origin=req.headers.get("origin")||"";const h:Record<string,string>={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer","vary":"Origin","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"GET,POST,OPTIONS"};if(origin&&ALLOWED.has(origin))h["access-control-allow-origin"]=origin;return h}
function J(req:Request,x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:headers(req)})}
function route(req:Request){return new URL(req.url).pathname.replace(/^.*\/legacy-auth-bridge/,"")||"/"}
function clientIp(req:Request){return String(req.headers.get("cf-connecting-ip")||(req.headers.get("x-forwarded-for")||"").split(",")[0]||req.headers.get("x-real-ip")||"unknown").trim().slice(0,128)}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function readBody(req:Request){const declared=Number(req.headers.get("content-length")||"0");if(Number.isFinite(declared)&&declared>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");const raw=await req.arrayBuffer();if(raw.byteLength>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");if(!raw.byteLength)return{} as Record<string,any>;try{const v=JSON.parse(new TextDecoder().decode(raw));if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v as Record<string,any>}catch{throw new AppError(400,"INVALID_JSON","JSON inválido.")}}
async function throttle(s:any,token:string,ip:string){const action="legacy_auth_exchange",tokenBucket="legacy-token:"+await sha(token),ipBucket="legacy-ip:"+await sha(ip),now=new Date(),since=new Date(now.getTime()-5*60_000).toISOString();const {error:ie}=await s.from("sns_auth_rate_limit_events").insert([{bucket_key:tokenBucket,action},{bucket_key:ipBucket,action}]);if(ie)throw ie;const [a,b]=await Promise.all([s.from("sns_auth_rate_limit_events").select("id",{head:true,count:"exact"}).eq("bucket_key",tokenBucket).eq("action",action).gte("created_at",since),s.from("sns_auth_rate_limit_events").select("id",{head:true,count:"exact"}).eq("bucket_key",ipBucket).eq("action",action).gte("created_at",since)]);if(a.error||b.error)throw a.error||b.error;if(Math.max(Number(a.count||0),Number(b.count||0))>20)throw new AppError(429,"RATE_LIMIT","Muitas trocas de sessão. Aguarde alguns minutos.")}
function syntheticEmail(id:string){return `legacy-${id.toLowerCase()}@accounts.naruto-unison.invalid`}
async function findUserByEmail(s:any,email:string){for(let page=1;page<=20;page++){const {data,error}=await s.auth.admin.listUsers({page,perPage:1000});if(error)throw error;const users=data?.users||[];const hit=users.find((u:any)=>String(u.email||"").toLowerCase()===email);if(hit)return hit;if(users.length<1000)break}return null}
async function ensureAuthUser(s:any,a:any){const {data:m,error:me}=await s.from("legacy_account_migrations").select("auth_user_id").eq("legacy_account_id",a.id).maybeSingle();if(me)throw me;if(m?.auth_user_id){const {data,error}=await s.auth.admin.getUserById(String(m.auth_user_id));if(error||!data?.user)throw new AppError(409,"AUTH_BINDING_BROKEN","O vínculo desta conta precisa de reparo administrativo.");return{user:data.user,needsMigration:false}}
 const email=syntheticEmail(String(a.id));let user=await findUserByEmail(s,email);if(!user){const random=crypto.getRandomValues(new Uint8Array(32));const password=btoa(String.fromCharCode(...random)).replace(/[+/=]/g,"A");const {data,error}=await s.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{username:a.user_name,legacyAccountId:a.id,legacyBridge:true}});if(error){user=await findUserByEmail(s,email);if(!user)throw error}else user=data.user}return{user,needsMigration:true}}
async function issueSession(s:any,user:any){const email=String(user?.email||"").trim().toLowerCase();if(!email)throw new AppError(409,"AUTH_EMAIL_MISSING","A identidade autenticada não possui e-mail interno.");const {data:link,error:le}=await s.auth.admin.generateLink({type:"magiclink",email});if(le)throw le;const tokenHash=String((link as any)?.properties?.hashed_token||"");if(!tokenHash)throw new Error("missing token hash");const {data,error}=await authClient().auth.verifyOtp({token_hash:tokenHash,type:"email"});if(error||!data?.session)throw error||new Error("missing auth session");return data.session}
async function migrateIfNeeded(req:Request,a:any,session:any,password:string){if(!password||password.length> PASSWORD_MAX)throw new AppError(400,"LEGACY_PASSWORD_REQUIRED","A senha atual é necessária apenas na primeira migração.");const r=await fetch(`${URL}/functions/v1/account-migration/claim`,{method:"POST",headers:{"content-type":"application/json","apikey":PUB,"authorization":`Bearer ${session.access_token}`},body:JSON.stringify({user:a.user_key,password})});const body=await r.json().catch(()=>({}));if(!r.ok||!body?.ok)throw new AppError(r.status>=400&&r.status<500?r.status:503,String(body?.code||"MIGRATION_FAILED"),String(body?.error||"Não foi possível migrar a conta para a identidade segura."));return body}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("",{status:204,headers:headers(req)});const origin=req.headers.get("origin")||"";if(origin&&!ALLOWED.has(origin))return J(req,{ok:false,code:"ORIGIN",error:"Origem não permitida."},403);try{const p=route(req);if(req.method==="GET"&&p==="/health")return J(req,{ok:true,service:"legacy-auth-bridge",version:"1"});if(req.method!=="POST"||p!=="/exchange")return J(req,{ok:false,code:"METHOD",error:"Rota inválida."},405);const b=await readBody(req),token=String(b.token||"").trim(),password=String(b.password||"");if(!TOKEN_RE.test(token))throw new AppError(401,"LEGACY_SESSION","Sessão antiga inválida ou expirada.");const s=admin();await throttle(s,token,clientIp(req));const {data:a,error:ae}=await s.from("naruto_accounts").select("id,user_name,user_key,session_token,banned").eq("session_token",token).maybeSingle();if(ae)throw ae;if(!a)throw new AppError(401,"LEGACY_SESSION","Sessão antiga inválida ou expirada.");if(a.banned)throw new AppError(403,"LEGACY_BANNED","Esta conta está suspensa.");const identity=await ensureAuthUser(s,a),session=await issueSession(s,identity.user);let migration:any=null;if(identity.needsMigration)migration=await migrateIfNeeded(req,a,session,password);return J(req,{ok:true,username:a.user_name,migrated:!!migration?.migrated,duplicate:!!migration?.duplicate,session:{access_token:session.access_token,refresh_token:session.refresh_token,expires_at:session.expires_at,expires_in:session.expires_in,token_type:session.token_type}})}catch(e:any){if(e instanceof AppError)return J(req,{ok:false,code:e.code,error:e.message},e.status);console.error("legacy-auth-bridge",e);return J(req,{ok:false,code:"AUTH_BRIDGE",error:"Falha interna ao criar a sessão segura."},503)}});