import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
const BODY_MAX=16*1024,ID_MAX=120,KEY_MAX=128,PERIOD_MAX=64;
const C={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type, x-idempotency-key","access-control-allow-methods":"POST,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String(o.default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const J=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:C});
class AppError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
const admin=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
async function user(req:Request){const a=req.headers.get("authorization")||"";if(!a.startsWith("Bearer "))throw new AppError(401,"AUTH","Sessão inválida.");const c=createClient(URL,PUB,{global:{headers:{Authorization:a}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new AppError(401,"AUTH","Sessão inválida.");return data.user}
async function body(req:Request){const declared=Number(req.headers.get("content-length")||"0");if(Number.isFinite(declared)&&declared>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");const raw=await req.arrayBuffer();if(raw.byteLength>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");if(!raw.byteLength)return{} as Record<string,any>;try{const v=JSON.parse(new TextDecoder().decode(raw));if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v as Record<string,any>}catch{throw new AppError(400,"INVALID_JSON","JSON inválido.")}}
function route(req:Request){const p=new URL(req.url).pathname;return p.replace(/^.*\/economy/,"")||"/"}
function id(v:unknown,label:string){const s=String(v||"").trim();if(!s||s.length>ID_MAX||/[\u0000-\u001f\u007f]/.test(s))throw new AppError(400,"INPUT",`${label} inválido.`);return s}
function key(req:Request){const raw=String(req.headers.get("x-idempotency-key")||"").trim()||crypto.randomUUID();if(raw.length>KEY_MAX||/[\u0000-\u001f\u007f]/.test(raw))throw new AppError(400,"IDEMPOTENCY_KEY","Chave de idempotência inválida.");return raw}
function mapDbError(e:any):AppError|null{const m=String(e?.message||"").toLowerCase();if(m.includes("insufficient ryo"))return new AppError(409,"INSUFFICIENT_RYO","Ryō insuficiente.");if(m.includes("objective not complete"))return new AppError(400,"OBJECTIVE_NOT_COMPLETE","Objetivo ainda não concluído.");if(m.includes("progress not found"))return new AppError(404,"PROGRESS_NOT_FOUND","Progresso não encontrado.");if(m.includes("reward entity not found")||m.includes("shop entity not found")||m.includes("equipment not found")||m.includes("equipment not owned"))return new AppError(404,"NOT_FOUND","Conteúdo ou equipamento não encontrado.");if(m.includes("not purchasable")||m.includes("quantity")||m.includes("unsupported reward kind"))return new AppError(400,"INVALID_OPERATION","Operação inválida.");return null}
async function view(db:any,userId:string){const [p,items,gear]=await Promise.all([db.from("profiles").select("ryo,xp,level").eq("user_id",userId).single(),db.from("player_items").select("item_id,qty").eq("user_id",userId),db.from("player_equipment").select("equipment_id,owned,durability").eq("user_id",userId)]);if(p.error)throw p.error;if(items.error)throw items.error;if(gear.error)throw gear.error;return{ryo:Number(p.data?.ryo||0),xp:Number(p.data?.xp||0),level:Number(p.data?.level||1),items:Object.fromEntries((items.data||[]).map((r:any)=>[r.item_id,Number(r.qty||0)])),equipment:Object.fromEntries((gear.data||[]).map((r:any)=>[r.equipment_id,{owned:!!r.owned,durability:Number(r.durability||0)}]))}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});try{if(req.method!=="POST")return J({ok:false,code:"METHOD",error:"Método inválido."},405);const u=await user(req),db=admin(),b=await body(req),r=route(req),idem=key(req);if(r==="/claim"){const kind=String(b.kind||b.source||"").trim(),entityId=id(b.entityId,"entityId"),period=String(b.period||"permanent").trim();if(!["task","achievement"].includes(kind)||!period||period.length>PERIOD_MAX||/[\u0000-\u001f\u007f]/.test(period))throw new AppError(400,"CLAIM","Claim inválido.");const {data,error}=await db.rpc("claim_progress_reward",{p_user_id:u.id,p_kind:kind,p_entity_id:entityId,p_period:period,p_idempotency_key:idem});if(error){const mapped=mapDbError(error);if(mapped)throw mapped;throw error}return J({ok:true,...data,economy:await view(db,u.id)})}if(r==="/purchase"){const itemId=id(b.itemId,"itemId"),qty=Number(b.qty??1);if(!Number.isInteger(qty)||qty<1||qty>99)throw new AppError(400,"QUANTITY","Quantidade deve ser de 1 a 99.");const {data,error}=await db.rpc("purchase_content_item",{p_user_id:u.id,p_item_id:itemId,p_qty:qty,p_idempotency_key:idem});if(error){const mapped=mapDbError(error);if(mapped)throw mapped;throw error}return J({ok:true,...data,economy:await view(db,u.id)})}if(r==="/repair"){const equipmentId=id(b.equipmentId,"equipmentId"),{data,error}=await db.rpc("repair_owned_equipment",{p_user_id:u.id,p_equipment_id:equipmentId,p_idempotency_key:idem});if(error){const mapped=mapDbError(error);if(mapped)throw mapped;throw error}return J({ok:true,...data,economy:await view(db,u.id)})}return J({ok:false,code:"ROUTE",error:"Rota desconhecida."},404)}catch(e:any){if(e instanceof AppError)return J({ok:false,code:e.code,error:e.message},e.status);console.error("economy",e);return J({ok:false,code:"ECONOMY_API",error:"Falha interna na economia."},503)}});
