import { balanceFactorForTechnique } from './balance-engine.js';
const CLAMP=(n,a,b)=>Math.max(a,Math.min(b,n));
export class MechanicsEngine{
 constructor({status,chakra,equipmentModifiers=null}={}){Object.assign(this,{status,chakra,equipmentModifiers});}
 resolve({state,actor,tech,targets}){
  const mechanics=Array.isArray(tech.mechanics)&&tech.mechanics.length?tech.mechanics:this.#legacy(tech);
  const outcomes=[];const metrics={damage:0,heal:0,shield:0,chakraDrain:0,statusApplied:0,cleanse:0};
  const balanceFactor=balanceFactorForTechnique(tech);
  for(const raw of mechanics){const m=this.#tune(raw,balanceFactor);this.#apply(m,{state,actor,tech,targets,outcomes,metrics,balanceFactor});}
  return{outcomes,metrics,mechanics,balanceFactor};
 }
 #apply(m,ctx){
  const targets=this.#targets(m,ctx);if(!targets.length)return;if(m.when&&!this.#condition(m.when,ctx,targets))return;
  switch(m.op){
   case'damage':for(const target of targets)this.#damage(target,m,ctx);break;
   case'heal':for(const target of targets)this.#heal(target,m,ctx);break;
   case'shield':for(const target of targets)this.#shield(target,m,ctx);break;
   case'status':for(const target of targets){const before=this.#snap(target),status=m.status||m.id||m.type||'status';this.status.apply(target,{id:status,type:m.status||m.type||'status',turns:Math.max(1,Number(m.turns||1)),value:Number(m.value||0),damage:Number(m.damage||0),stacks:Number(m.stacks||1),sourceTechniqueId:ctx.tech.id,tags:m.tags||[]});ctx.metrics.statusApplied++;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'status',status,value:Number(m.value||m.damage||1),actual:1,mechanic:'status'});}break;
   case'buff':for(const target of targets){const before=this.#snap(target);this.status.apply(target,{id:`buff:${m.stat}:${ctx.tech.id}`,type:'buff',stat:m.stat,amount:Number(m.amount||0),turns:Math.max(1,Number(m.turns||1)),sourceTechniqueId:ctx.tech.id});ctx.outcomes.push({target,before,after:this.#snap(target),kind:'buff',stat:m.stat,value:Number(m.amount||0),actual:Number(m.amount||0),mechanic:'buff'});}break;
   case'debuff':for(const target of targets){const before=this.#snap(target);this.status.apply(target,{id:`debuff:${m.stat}:${ctx.tech.id}`,type:'debuff',stat:m.stat,amount:Number(m.amount||0),turns:Math.max(1,Number(m.turns||1)),sourceTechniqueId:ctx.tech.id});ctx.outcomes.push({target,before,after:this.#snap(target),kind:'debuff',stat:m.stat,value:Number(m.amount||0),actual:Number(m.amount||0),mechanic:'debuff'});}break;
   case'cleanse':for(const target of targets){const before=this.#snap(target),bad=(target.statuses||[]).filter(s=>this.#hostile(s)),n=Math.min(bad.length,Math.max(1,Number(m.count||1)));for(const s of bad.slice(0,n))target.statuses.splice(target.statuses.indexOf(s),1);ctx.metrics.cleanse+=n;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'cleanse',value:n,actual:n,mechanic:'cleanse'});}break;
   case'dispel':for(const target of targets){const before=this.#snap(target),good=(target.statuses||[]).filter(s=>this.#beneficial(s)),n=Math.min(good.length,Math.max(1,Number(m.count||1)));for(const s of good.slice(0,n))target.statuses.splice(target.statuses.indexOf(s),1);ctx.outcomes.push({target,before,after:this.#snap(target),kind:'dispel',value:n,actual:n,mechanic:'dispel'});}break;
   case'chakra-drain':for(const target of targets){const pool=ctx.state.chakra[target.side],beforePool={...pool};let left=Math.max(1,Number(m.amount||1)),taken=0;for(const k of ['NIN','TAI','GEN','KEK'].sort((a,b)=>pool[b]-pool[a])){const take=Math.min(pool[k],left);pool[k]-=take;left-=take;taken+=take;ctx.metrics.chakraDrain+=take;if(left<=0)break;}ctx.outcomes.push({target,before:this.#snap(target),after:this.#snap(target),beforePool,afterPool:{...pool},kind:'chakra-drain',value:taken,actual:taken,mechanic:'chakra-drain'});}break;
   case'chakra-gain':{
    const side=(m.target==='enemy'||m.target==='all-enemies')?(ctx.actor.side==='you'?'ai':'you'):ctx.actor.side,pool=ctx.state.chakra[side],beforePool={...pool};let n=Math.max(1,Number(m.amount||1)),gained=0;while(n--){const k=m.type&&pool[m.type]!=null?m.type:['NIN','TAI','GEN','KEK'].sort((a,b)=>pool[a]-pool[b])[0],before=pool[k];pool[k]=Math.min(9,pool[k]+1);gained+=pool[k]-before;}const target=side===ctx.actor.side?ctx.actor:targets[0];ctx.outcomes.push({target,before:this.#snap(target),after:this.#snap(target),beforePool,afterPool:{...pool},kind:'chakra-gain',value:gained,actual:gained,mechanic:'chakra-gain'});break;
   }
   case'cooldown':for(const target of targets){let changed=0;for(const id of Object.keys(target.cooldowns||{})){const before=Number(target.cooldowns[id]||0),after=CLAMP(before+Number(m.amount||0),0,9);target.cooldowns[id]=after;changed+=Math.abs(after-before);}ctx.outcomes.push({target,before:this.#snap(target),after:this.#snap(target),kind:'cooldown',value:changed,actual:changed,mechanic:'cooldown'});}break;
   case'execute':for(const target of targets){if(target.hp/Math.max(1,target.maxHp)<=Number(m.threshold||.25))this.#damage(target,{...m,amount:Number(m.amount||m.power||20),ignoreShield:!!m.ignoreShield},ctx);}break;
   case'drain':for(const target of targets){const before=target.hp;this.#damage(target,{...m,amount:Number(m.amount||20)},ctx);const dealt=Math.max(0,before-target.hp),heal=Math.round(dealt*Number(m.ratio||.5)),healBefore=this.#snap(ctx.actor);ctx.actor.hp=Math.min(ctx.actor.maxHp,ctx.actor.hp+heal);ctx.metrics.heal+=heal;ctx.outcomes.push({target:ctx.actor,before:healBefore,after:this.#snap(ctx.actor),kind:'heal',value:heal,actual:heal,mechanic:'drain-heal'});}break;
   case'mark':for(const target of targets){const before=this.#snap(target),mark=m.mark||ctx.tech.id;this.status.apply(target,{id:`mark:${mark}`,type:'mark',mark,turns:Math.max(1,Number(m.turns||2)),sourceTechniqueId:ctx.tech.id});ctx.metrics.statusApplied++;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'mark',status:mark,value:1,actual:1,mechanic:'mark'});}break;
   case'multi-hit':{const hits=CLAMP(Number(m.hits||2),2,8),each={...m,op:'damage',amount:Number(m.amount||m.power||ctx.tech.power||10)/hits};for(let i=0;i<hits;i++)for(const target of targets)this.#damage(target,each,ctx);break;}
  }
 }
 #tune(m,f){if(!m||Math.abs(f-1)<.005)return m;const x={...m};for(const k of ['amount','power','damage'])if(Number.isFinite(Number(x[k])))x[k]=Math.max(0,Math.round(Number(x[k])*f));if(['buff','debuff'].includes(x.op)&&Number.isFinite(Number(x.amount)))x.amount=Math.max(1,Math.round(Number(x.amount)*f));if(x.op==='status'&&Number.isFinite(Number(x.value))&&Math.abs(Number(x.value))<=1)x.value=CLAMP(Number(x.value)*f,0,.75);return x;}
 #damage(target,m,ctx){const before=this.#snap(target);let amount=Number(m.amount??m.power??ctx.tech.power??10);amount+=this.#stat(ctx.actor,'attack')*Number(m.attackScale??.22);amount-=this.#stat(target,'defense')*Number(m.defenseScale??.10);if(m.bonusIf&&this.#condition(m.bonusIf,ctx,[target]))amount*=Number(m.bonusMultiplier||1.25);amount=Math.max(0,Math.round(amount));if((ctx.actor.statuses||[]).some(s=>s.type==='blind'&&s.turns>0))amount=Math.round(amount*.55);amount=Math.round(amount*this.#damageTakenMultiplier(target));amount=this.equipmentModifiers?.modifyOutcome?.({kind:'damage',value:amount,actor:ctx.actor,target})??amount;const evade=(target.statuses||[]).find(s=>['evasion','substitution'].includes(s.type)&&s.turns>0);if(evade&&!m.ignoreEvasion){target.statuses.splice(target.statuses.indexOf(evade),1);amount=0;}if((target.statuses||[]).some(s=>s.type==='invuln'&&s.turns>0))amount=0;const absorbed=m.ignoreShield?0:Math.min(target.shield||0,amount);if(!m.ignoreShield)target.shield=Math.max(0,(target.shield||0)-absorbed);target.hp=Math.max(0,target.hp-(amount-absorbed));const actual=Math.max(0,before.hp-target.hp);ctx.metrics.damage+=actual;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'damage',value:amount,actual,absorbed,mechanic:m.op||'damage'});const counter=(target.statuses||[]).find(s=>s.type==='counter'&&s.turns>0);if(counter&&actual>0&&target!==ctx.actor){const reflected=Math.max(1,Math.round(actual*Number(counter.value||.25))),counterBefore=this.#snap(ctx.actor);ctx.actor.hp=Math.max(0,ctx.actor.hp-reflected);ctx.outcomes.push({target:ctx.actor,before:counterBefore,after:this.#snap(ctx.actor),kind:'counter',value:reflected,actual:reflected,mechanic:'counter'});target.statuses.splice(target.statuses.indexOf(counter),1);}}
 #heal(target,m,ctx){const before=this.#snap(target);let amount=Math.max(0,Math.round(Number(m.amount??m.power??ctx.tech.power??20)+this.#stat(ctx.actor,'support')*Number(m.supportScale??.20)));amount=this.equipmentModifiers?.modifyOutcome?.({kind:'heal',value:amount,actor:ctx.actor,target})??amount;amount=Math.min(target.maxHp-target.hp,amount);target.hp+=amount;ctx.metrics.heal+=amount;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'heal',value:amount,actual:amount,mechanic:'heal'});}
 #shield(target,m,ctx){const before=this.#snap(target),amount=Math.max(0,Math.round(Number(m.amount??m.power??ctx.tech.power??20)));target.shield=(target.shield||0)+amount;ctx.metrics.shield+=amount;ctx.outcomes.push({target,before,after:this.#snap(target),kind:'shield',value:amount,actual:amount,mechanic:'shield'});if(m.turns)this.status.apply(target,{id:`shield:${ctx.tech.id}`,type:'shield-duration',turns:Number(m.turns),amount,sourceTechniqueId:ctx.tech.id});}
 #targets(m,{actor,targets,state}){switch(m.target){case'self':return[actor];case'allies':case'all-allies':return(actor.side==='you'?state.you:state.ai).filter(x=>x.hp>0);case'enemies':case'all-enemies':return(actor.side==='you'?state.ai:state.you).filter(x=>x.hp>0);case'primary':default:return targets;}}
 #condition(w,{actor,state},targets){const t=targets[0];if(!w)return true;if(w.targetHas)return(t?.statuses||[]).some(s=>s.type===w.targetHas||s.id===w.targetHas||s.mark===w.targetHas);if(w.targetMissing)return!(t?.statuses||[]).some(s=>s.type===w.targetMissing||s.id===w.targetMissing);if(w.targetHpBelow!=null)return!!t&&t.hp/Math.max(1,t.maxHp)<=Number(w.targetHpBelow);if(w.selfHpBelow!=null)return actor.hp/Math.max(1,actor.maxHp)<=Number(w.selfHpBelow);if(w.selfHas)return(actor.statuses||[]).some(s=>s.type===w.selfHas||s.id===w.selfHas);if(w.enemyStatusCountAtLeast!=null)return targets.reduce((n,x)=>n+(x.statuses?.length||0),0)>=Number(w.enemyStatusCountAtLeast);return true;}
 #stat(f,stat){let v=Number(f.stats?.[stat]||0);for(const s of f.statuses||[]){if(s.type==='buff'&&s.stat===stat)v+=Number(s.amount||0);if(s.type==='debuff'&&s.stat===stat)v-=Number(s.amount||0);}return v;}
 #damageTakenMultiplier(f){let m=1;for(const s of f.statuses||[]){if(s.type==='vulnerable')m+=Number(s.value||.15);if(s.type==='guarded')m-=Number(s.value||.10);}return Math.max(.25,m);}
 #hostile(s){return['dot','burn','poison','bleed','stun','sleep','bind','silence','chakra-lock','vulnerable','debuff','mark','soaked','shock','freeze'].includes(s.type);}
 #beneficial(s){return['buff','regen','invuln','evasion','substitution','guarded','counter','shield-duration'].includes(s.type);}
 #snap(f){return{hp:f.hp,shield:f.shield,statuses:structuredClone(f.statuses||[])};}
 #legacy(t){const e=t.effect||{},p=Number(e.power??t.power??0);if(e.kind==='heal')return[{op:'heal',amount:p,target:'primary'}];if(e.kind==='shield')return[{op:'shield',amount:p,target:'primary',turns:e.duration||0}];if(e.kind==='invuln')return[{op:'status',status:'invuln',turns:e.duration||1,target:'primary'}];if(e.kind==='stun')return[{op:'damage',amount:p,target:'primary'},{op:'status',status:'stun',turns:e.duration||1,target:'primary'}];if(e.kind==='dot')return[{op:'damage',amount:Math.round(p*.65),target:'primary'},{op:'status',status:'dot',damage:Math.max(1,Math.round(p*.18)),turns:e.duration||2,target:'primary'}];return[{op:'damage',amount:p,target:'primary'}];}
}
