import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String((o as any).default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const C={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"GET,POST,PATCH,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const HUMAN_ROLES=new Set(["MODERATOR","CONTENT","ADMIN","OWNER"]);
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
class E extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});
const db=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
async function actor(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new E(401,"AUTH","Sessão inválida.");const c=createClient(URL,PUB,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new E(401,"AUTH","Sessão inválida.");return data.user}
async function allow(req:Request,d:any,permission:string){const u=await actor(req);const {data,error}=await d.rpc("authorize_as_user",{p_user_id:u.id,p_permission:permission});if(error)throw new E(503,"AUTHZ","Autorização indisponível.");if(!data)throw new E(403,"PERMISSION","Permissão insuficiente.");return u}
async function principal(d:any,userId:string){const {data,error}=await d.from("admin_principals").select("id,user_id,display_name,active").eq("user_id",userId).maybeSingle();if(error)throw error;return data}
async function rolesFor(d:any,principalIds:string[]){if(!principalIds.length)return new Map<string,string[]>();const {data,error}=await d.from("admin_principal_roles").select("principal_id,role").in("principal_id",principalIds);if(error)throw error;const m=new Map<string,string[]>();for(const r of data||[]){const a=m.get(r.principal_id)||[];a.push(String(r.role));m.set(r.principal_id,a)}return m}
async function countActiveOwners(d:any){const {data:rows,error}=await d.from("admin_principal_roles").select("principal_id,admin_principals!inner(active)").eq("role","OWNER");if(error)throw error;return (rows||[]).filter((x:any)=>x.admin_principals?.active).length}
async function audit(d:any,principalId:string|null,action:string,targetId:string,before:unknown,after:unknown){const {error}=await d.from("admin_audit_log").insert({principal_id:principalId,action,target_type:"admin_principal",target_id:targetId,before,after});if(error)throw error}
function path(req:Request){const p=new URL(req.url).pathname;return p.replace(/^.*\/admin-studio-api/,"")||"/"}
async function body(req:Request){const raw=await req.text();if(raw.length>65536)throw new E(413,"BODY","Corpo excede o limite.");if(!raw)return{};try{const v=JSON.parse(raw);if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v}catch{throw new E(400,"JSON","JSON inválido.")}}
function cleanRoles(v:unknown){if(!Array.isArray(v))throw new E(400,"ROLES","Papéis inválidos.");const out=[...new Set(v.map(String).map(x=>x.toUpperCase()).filter(x=>HUMAN_ROLES.has(x)))];if(!out.length)throw new E(400,"ROLES","Selecione ao menos um papel administrativo.");return out}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("",{status:204,headers:C});try{const d=db(),r=path(req);
  if(r==="/versions"&&req.method==="GET"){await allow(req,d,"content.read");const u=new URL(req.url),type=(u.searchParams.get("type")||"").trim(),id=(u.searchParams.get("id")||"").trim();if(!type||!id||type.length>64||id.length>160)throw new E(400,"INPUT","Tipo/ID inválido.");const {data,error}=await d.from("content_versions").select("version,message,created_by,created_at").eq("entity_type",type).eq("entity_id",id).order("version",{ascending:false}).limit(100);if(error)throw error;return J({ok:true,versions:data||[]})}
  if(r==="/roles"&&req.method==="GET"){await allow(req,d,"admin.roles");const {data,error}=await d.from("admin_role_permissions").select("role,permission");if(error)throw error;const matrix:Record<string,string[]>={};for(const x of data||[]){const k=String(x.role);(matrix[k]??=[]).push(String(x.permission))}for(const k of Object.keys(matrix))matrix[k].sort();return J({ok:true,allowedRoles:[...HUMAN_ROLES],permissions:matrix})}
  if(r==="/principals"&&req.method==="GET"){await allow(req,d,"admin.roles");const {data,error}=await d.from("admin_principals").select("id,user_id,principal_type,display_name,active,created_at").order("created_at",{ascending:true});if(error)throw error;const ids=(data||[]).map((x:any)=>x.id);const rm=await rolesFor(d,ids);return J({ok:true,principals:(data||[]).map((x:any)=>({...x,roles:rm.get(x.id)||[]}))})}
  if(r==="/principals"&&req.method==="POST"){const u=await allow(req,d,"admin.roles"),ap=await principal(d,u.id),b:any=await body(req),userId=String(b.userId||"");if(!UUID.test(userId))throw new E(400,"USER","userId inválido.");const roles=cleanRoles(b.roles),name=String(b.displayName||"").trim().slice(0,120);if(!name)throw new E(400,"NAME","Nome administrativo obrigatório.");const {data:authUser,error:ae}=await d.auth.admin.getUserById(userId);if(ae||!authUser?.user)throw new E(404,"USER","Usuário Auth não encontrado.");const {data:exists,error:ee}=await d.from("admin_principals").select("*").eq("user_id",userId).maybeSingle();if(ee)throw ee;if(exists)throw new E(409,"EXISTS","Usuário já possui principal administrativo.");const {data:p,error:pe}=await d.from("admin_principals").insert({user_id:userId,principal_type:"user",display_name:name,active:true}).select("*").single();if(pe)throw pe;const {error:re}=await d.from("admin_principal_roles").insert(roles.map(role=>({principal_id:p.id,role})));if(re){await d.from("admin_principals").delete().eq("id",p.id);throw re}await audit(d,ap?.id||null,"admin.principal.create",p.id,null,{...p,roles});return J({ok:true,principal:{...p,roles}},201)}
  const pm=r.match(/^\/principals\/([0-9a-f-]+)$/i);if(pm&&req.method==="PATCH"){const u=await allow(req,d,"admin.roles"),ap=await principal(d,u.id),id=pm[1];if(!UUID.test(id))throw new E(400,"ID","Principal inválido.");const b:any=await body(req),{data:before,error:be}=await d.from("admin_principals").select("*").eq("id",id).maybeSingle();if(be)throw be;if(!before)throw new E(404,"PRINCIPAL","Principal ausente.");const oldRoles=(await rolesFor(d,[id])).get(id)||[];const nextRoles=b.roles===undefined?oldRoles:cleanRoles(b.roles),active=b.active===undefined?!!before.active:!!b.active,displayName=b.displayName===undefined?before.display_name:String(b.displayName||"").trim().slice(0,120);if(!displayName)throw new E(400,"NAME","Nome inválido.");const losesOwner=oldRoles.includes("OWNER")&&(!nextRoles.includes("OWNER")||!active);if(losesOwner&&await countActiveOwners(d)<=1)throw new E(409,"LAST_OWNER","O último OWNER ativo não pode ser removido ou desativado.");if(before.user_id===u.id&&oldRoles.includes("OWNER")&&!nextRoles.includes("OWNER"))throw new E(409,"SELF_OWNER","O OWNER atual não pode remover seu próprio papel OWNER.");const {data:afterBase,error:ue}=await d.from("admin_principals").update({display_name:displayName,active}).eq("id",id).select("*").single();if(ue)throw ue;if(b.roles!==undefined){const {error:de}=await d.from("admin_principal_roles").delete().eq("principal_id",id);if(de)throw de;const {error:ie}=await d.from("admin_principal_roles").insert(nextRoles.map(role=>({principal_id:id,role})));if(ie)throw ie}const after={...afterBase,roles:nextRoles};await audit(d,ap?.id||null,"admin.principal.update",id,{...before,roles:oldRoles},after);return J({ok:true,principal:after})}
  return J({ok:false,code:"ROUTE",error:"Rota desconhecida."},404)
}catch(e:any){if(e instanceof E)return J({ok:false,code:e.code,error:e.message},e.status);console.error("admin-studio-api",e);return J({ok:false,code:"INTERNAL",error:"Falha interna do Admin Studio."},503)}});
