import { balanceLabel } from '../../domains/battle/balance-engine.js';
import { BattleEvent as E } from '../../domains/battle/battle-events.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
export class BattleUi{
 constructor({bus,engine,content,store,root=document.body}={}){Object.assign(this,{bus,engine,content,store,root});this.ctrl=new AbortController();this.pending=[];this.targeting=null;}
 start(){const o={signal:this.ctrl.signal};this.bus.on(E.START,p=>{if(!p.state?.remoteRaid)this.mount(p.state)},o);this.bus.on(E.RESOLVED,()=>this.render(),o);this.bus.on(E.ITEM_USED,()=>this.render(),o);this.bus.on(E.TURN_START,()=>{this.pending=[];this.targeting=null;this.render();},o);this.bus.on(E.END,p=>this.end(p),o);}
 stop(){this.ctrl.abort();this.dialog?.remove();}
 mount(){this.dialog=document.createElement('dialog');this.dialog.className='battleDialog';this.dialog.innerHTML=`<div class="battleStage" data-battle-stage><header><div><small data-battle-mode></small><h2>COMBATE SHINOBI</h2></div><div data-chakra></div></header><div class="battleTargetPrompt" data-target-prompt hidden></div><section class="battleTeams"><div data-team="you"></div><div data-team="ai"></div></section><section class="battleControls"><div data-techniques></div><div data-items></div><div class="battleQueue" data-queue></div><div class="battleMainActions"><button data-cancel-target hidden>CANCELAR ALVO</button><button data-confirm>CONFIRMAR TURNO</button><button data-skip>PULAR TURNO</button></div></section><aside data-battle-log></aside></div>`;document.body.append(this.dialog);this.dialog.showModal();this.dialog.querySelector('[data-confirm]').onclick=()=>this.confirm();this.dialog.querySelector('[data-skip]').onclick=()=>this.skip();this.dialog.querySelector('[data-cancel-target]').onclick=()=>{this.targeting=null;this.render()};this.render();}
 render(){if(!this.dialog||!this.engine.state)return;const s=this.engine.state;this.dialog.querySelector('[data-battle-mode]').textContent=`${s.mode.toUpperCase()} • TURNO ${s.turn}`;this.dialog.querySelector('[data-chakra]').innerHTML=Object.entries(s.chakra.you).map(([k,v])=>`<b>${k} ${v}</b>`).join(' ');const targetIds=new Set(this.targeting?.validIds||[]);for(const side of ['you','ai']){const root=this.dialog.querySelector(`[data-team="${side}"]`);root.innerHTML=s[side].map(f=>{const c=this.content.get('character',f.characterId),img=c?.image||'static/img/icon.png';return `<button type="button" class="fighterCard ${targetIds.has(f.id)?'is-targetable':''}" data-fighter-id="${esc(f.id)}" data-side="${side}" ${targetIds.has(f.id)?'':'disabled'}><img class="fighterPortrait" src="${esc(img)}" alt=""><div class="fighterInfo"><b>${esc(f.name)}</b><small>${f.hp}/${f.maxHp} PV${f.shield?` • ${f.shield} ESCUDO`:''}</small><div class="hp"><i style="width:${Math.max(0,f.hp/f.maxHp*100)}%"></i></div></div>${targetIds.has(f.id)?'<em>ESCOLHER ALVO</em>':''}</button>`}).join('');root.querySelectorAll('.is-targetable').forEach(b=>b.onclick=()=>this.chooseTarget(b.dataset.fighterId));}
 const actor=s.you.find(f=>f.hp>0&&!this.pending.some(a=>a.actorId===f.id));const techRoot=this.dialog.querySelector('[data-techniques]');techRoot.innerHTML=actor&&!this.targeting?actor.skills.map(t=>`<button data-tech="${esc(t.id)}"><img src="${esc(t.image||'static/img/icon.png')}" alt=""><span><b>${esc(t.name)}</b><small>${esc((t.chakraCost||[]).join('+')||'SEM CHAKRA')} • CD ${t.cooldown||0}${balanceLabel(t)?` • ${esc(balanceLabel(t))}`:''}</small></span></button>`).join(''):this.targeting?'<em>Escolha um alvo destacado no campo.</em>':'<em>Ações da equipe selecionadas.</em>';techRoot.querySelectorAll('[data-tech]').forEach(b=>b.onclick=()=>this.pickTechnique(actor,b.dataset.tech));
 const itemRoot=this.dialog.querySelector('[data-items]'),profile=this.store?.state?.profile;itemRoot.innerHTML=actor&&!this.targeting?Object.entries(profile?.items||{}).filter(([,q])=>q>0).slice(0,8).map(([id,q])=>{const it=this.content.get('item',id);return it&&it.allowedModes?.includes(s.mode)?`<button data-item="${esc(id)}"><img src="${esc(it.image)}" alt=""><span>${esc(it.name)} ×${q}</span><small>${esc(it.description||'')}</small></button>`:'';}).join(''):'';itemRoot.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>this.pickItem(actor,b.dataset.item));
 this.dialog.querySelector('[data-queue]').innerHTML=this.pending.length?this.pending.map(a=>`<span>${esc(s.you.find(f=>f.id===a.actorId)?.name)} → ${a.type==='item'?esc(this.content.get('item',a.itemId)?.name):esc(s.you.find(f=>f.id===a.actorId)?.skills.find(t=>t.id===a.techniqueId)?.name)} → ${esc(this.findFighter(a.targetIds?.[0])?.name||'alvo')}</span>`).join(''):'<span>Nenhuma ação na fila.</span>';
 const prompt=this.dialog.querySelector('[data-target-prompt]'),cancel=this.dialog.querySelector('[data-cancel-target]');prompt.hidden=!this.targeting;cancel.hidden=!this.targeting;if(this.targeting)prompt.innerHTML=`<b>ESCOLHA O ALVO</b><span>${esc(this.targeting.label)} • ${this.targeting.validIds.length} alvo(s) válido(s)</span>`;this.dialog.querySelector('[data-confirm]').disabled=!!this.targeting||!this.pending.length;this.dialog.querySelector('[data-battle-log]').innerHTML=s.log.slice(-8).map(x=>`<div>T${x.turn} • ${esc(x.type==='item'?this.content.get('item',x.itemId)?.name||x.itemId:this.findTechnique(x.actorId,x.techniqueId)?.name||x.techniqueId)}</div>`).join('');}
 pickTechnique(actor,id){if(!actor)return;const t=actor.skills.find(x=>x.id===id),targets=this.engine.rules.validTargets(this.engine.state,actor,t);if(!targets.length)return;if(targets.length===1&&(t.target==='self'||t.target==='all-allies'||t.target==='all-enemies'))return this.queue({type:'jutsu',actorId:actor.id,techniqueId:id,targetIds:[targets[0].id]});this.targeting={type:'jutsu',actorId:actor.id,techniqueId:id,label:t.name,validIds:targets.map(x=>x.id)};this.render();}
 pickItem(actor,id){if(!actor)return;const it=this.content.get('item',id),s=this.engine.state,allies=s.you.filter(f=>f.hp>0),enemies=s.ai.filter(f=>f.hp>0),targets=it.target==='enemy'?enemies:it.target==='ally'?allies:[actor];if(!targets.length)return;if(targets.length===1||it.target==='self')return this.queue({type:'item',actorId:actor.id,itemId:id,targetIds:[targets[0].id]});this.targeting={type:'item',actorId:actor.id,itemId:id,label:it.name,validIds:targets.map(x=>x.id)};this.render();}
 chooseTarget(id){if(!this.targeting||!this.targeting.validIds.includes(id))return;const t=this.targeting;this.targeting=null;this.queue({...t,targetIds:[id]});}
 queue(a){delete a.label;delete a.validIds;this.pending=this.pending.filter(x=>x.actorId!==a.actorId);this.pending.push(a);this.render();}
 findFighter(id){const s=this.engine.state;return[...(s?.you||[]),...(s?.ai||[])].find(x=>x.id===id)}
 findTechnique(actorId,id){return this.findFighter(actorId)?.skills.find(x=>x.id===id)}
 async confirm(){if(this.targeting||!this.pending.length)return;this.setDisabled(true);try{for(const action of this.pending)if(!this.engine.state.winner)await this.engine.perform(action);this.pending=[];this.bus.emit('battle:player-actions:done',{state:this.engine.state});}finally{this.setDisabled(false);this.render();}}
 async skip(){this.targeting=null;this.pending=[];this.bus.emit('battle:player-actions:done',{state:this.engine.state,skipped:true});}
 setDisabled(v){this.dialog?.querySelectorAll('button').forEach(b=>b.disabled=v);}
 end({result}){if(!this.dialog)return;this.targeting=null;this.pending=[];this.dialog.querySelector('.battleControls').innerHTML=`<div class="battleResult"><h2>${result.ok?'VITÓRIA':'DERROTA'}</h2>${result.reward?`<p><b>+${result.reward.ryo} Ryō</b> • +${result.reward.xp} XP</p><p>${(result.reward.drops||[]).map(d=>`${d.qty||1}× ${esc(this.content.get(d.type,d.id)?.name||d.id)}`).join(' • ')}</p>`:''}<button data-close>CONTINUAR</button></div>`;this.dialog.querySelector('[data-close]').onclick=()=>{this.dialog.close();this.dialog.remove();this.dialog=null;};}
}
