import { MongoClient, ObjectId } from "mongodb";

const enc = new TextEncoder();
const dec = new TextDecoder();
const jsonHeaders = { "content-type": "application/json; charset=utf-8" };
function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function unb64url(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
async function hmac(secret,data){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(data)));}
async function issueToken(env,user){const payload=b64url(enc.encode(JSON.stringify({sub:String(user._id),usr:user.username,exp:Date.now()+2592000000})));return payload+"."+b64url(await hmac(env.AUTH_SECRET,payload));}
async function verifyToken(env,token){if(!token||!token.includes("."))return null;const [p,s]=token.split("."),e=b64url(await hmac(env.AUTH_SECRET,p));if(s.length!==e.length)return null;let d=0;for(let i=0;i<s.length;i++)d|=s.charCodeAt(i)^e.charCodeAt(i);if(d!==0)return null;try{const o=JSON.parse(dec.decode(unb64url(p)));return o.exp&&o.exp>=Date.now()?o:null;}catch{return null;}}
async function hashPassword(password,salt,iterations=210000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return b64url(new Uint8Array(bits));}
function randomBytes(n=16){const a=new Uint8Array(n);crypto.getRandomValues(a);return a;}
function norm(v){return String(v||"").trim();}
function safeUser(u){return{id:String(u._id),username:u.username,createdAt:u.createdAt};}
function cors(req,env){const origin=req.headers.get("origin")||"",allowed=[env.ALLOWED_ORIGIN,"http://localhost:8000","http://127.0.0.1:8000"].filter(Boolean);return{"access-control-allow-origin":allowed.includes(origin)?origin:(origin?"null":(env.ALLOWED_ORIGIN||"*")),"access-control-allow-methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","access-control-allow-headers":"authorization,content-type","access-control-max-age":"86400","vary":"origin"};}
function reply(req,env,status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...jsonHeaders,...cors(req,env),...extra}});}
async function bodyJson(req){try{return await req.json();}catch{return{};}}
function bearer(req){const h=req.headers.get("authorization")||"";return h.toLowerCase().startsWith("bearer ")?h.slice(7).trim():"";}
async function auth(req,env,db){const p=await verifyToken(env,bearer(req));if(!p)return null;let id;try{id=new ObjectId(p.sub);}catch{return null;}return db.collection("users").findOne({_id:id});}
async function ensureIndexes(db){await Promise.all([db.collection("users").createIndex({usernameLower:1},{unique:true,name:"uq_username"}),db.collection("saves").createIndex({userId:1},{unique:true,name:"uq_save_user"}),db.collection("friends").createIndex({ownerId:1,friendId:1},{unique:true,name:"uq_friend"}),db.collection("online_actions").createIndex({createdAt:-1},{name:"ix_actions_time"}),db.collection("rooms").createIndex({mode:1,updatedAt:-1},{name:"ix_rooms_mode_time"})]);}
async function roomRoute(req,env,db,user,mode,path){const rooms=db.collection("rooms"),actions=db.collection("online_actions"),b=await bodyJson(req),action=path.split("/").filter(Boolean).pop();if(action==="create"){const now=new Date(),doc={mode,ownerId:user._id,members:[user._id],state:b.state||{},status:"open",createdAt:now,updatedAt:now},r=await rooms.insertOne(doc);return reply(req,env,200,{ok:true,roomId:String(r.insertedId),room:{...doc,_id:String(r.insertedId)}});}if(action==="join"){let rid;try{rid=new ObjectId(b.roomId);}catch{return reply(req,env,400,{ok:false,error:"ROOM_ID_INVALID"});}await rooms.updateOne({_id:rid,mode},{$addToSet:{members:user._id},$set:{updatedAt:new Date()}});const room=await rooms.findOne({_id:rid,mode});return reply(req,env,room?200:404,{ok:!!room,room:room?{...room,_id:String(room._id)}:null});}if(action==="state"){let q={mode};if(b.roomId){try{q._id=new ObjectId(b.roomId);}catch{return reply(req,env,400,{ok:false,error:"ROOM_ID_INVALID"});}}const room=await rooms.findOne(q,{sort:{updatedAt:-1}});return reply(req,env,200,{ok:true,room:room?{...room,_id:String(room._id)}:null});}if(action==="action"){let roomId=null;if(b.roomId){try{roomId=new ObjectId(b.roomId);}catch{return reply(req,env,400,{ok:false,error:"ROOM_ID_INVALID"});}}const now=new Date();await actions.insertOne({mode,roomId,userId:user._id,action:b.action??b,createdAt:now});if(roomId)await rooms.updateOne({_id:roomId,mode},{$set:{updatedAt:now},$push:{log:{$each:[{userId:String(user._id),action:b.action??b,at:now}],$slice:-100}}});return reply(req,env,200,{ok:true,accepted:true,serverTime:now.toISOString()});}return reply(req,env,404,{ok:false,error:"ROOM_ROUTE_NOT_FOUND"});}

export default {async fetch(req,env){
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req,env)});
  const url=new URL(req.url),path=url.pathname.replace(/\/+$/g,"")||"/";
  if(path==="/"||path==="/api/status")return reply(req,env,200,{ok:true,service:"naruto-shinobi-r41-api",build:"R41-CLOUDFLARE-MONGODB-20260819",configured:!!(env.MONGODB_URI&&env.AUTH_SECRET)});
  if(!env.MONGODB_URI||!env.AUTH_SECRET)return reply(req,env,503,{ok:false,error:"SERVER_NOT_CONFIGURED"});
  const client=new MongoClient(env.MONGODB_URI,{maxPoolSize:3,minPoolSize:0,serverSelectionTimeoutMS:5000,connectTimeoutMS:5000});
  try{
    await client.connect();const db=client.db(env.MONGODB_DB||"naruto_shinobi_r41");await ensureIndexes(db);
    if(path==="/api/auth/register"&&req.method==="POST"){const b=await bodyJson(req),username=norm(b.username),password=String(b.password||"");if(username.length<3||username.length>32||password.length<8)return reply(req,env,400,{ok:false,error:"INVALID_CREDENTIALS_FORMAT"});const salt=randomBytes(),passHash=await hashPassword(password,salt),now=new Date();let r;try{r=await db.collection("users").insertOne({username,usernameLower:username.toLowerCase(),passSalt:b64url(salt),passHash,passIter:210000,createdAt:now});}catch(e){if(e&&e.code===11000)return reply(req,env,409,{ok:false,error:"USERNAME_EXISTS"});throw e;}const user={_id:r.insertedId,username,createdAt:now};return reply(req,env,201,{ok:true,token:await issueToken(env,user),user:safeUser(user)});}
    if(path==="/api/auth/login"&&req.method==="POST"){const b=await bodyJson(req),username=norm(b.username),password=String(b.password||""),u=await db.collection("users").findOne({usernameLower:username.toLowerCase()});if(!u)return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});const got=await hashPassword(password,unb64url(u.passSalt),u.passIter||210000);if(got!==u.passHash)return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});return reply(req,env,200,{ok:true,token:await issueToken(env,u),user:safeUser(u)});}
    const user=await auth(req,env,db);
    if(path==="/api/auth/me")return user?reply(req,env,200,{ok:true,user:safeUser(user)}):reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
    if(!user)return reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
    if(path==="/api/account/save"&&["POST","PUT"].includes(req.method)){const b=await bodyJson(req),data=b.save??b.data??b,now=new Date();await db.collection("saves").updateOne({userId:user._id},{$set:{userId:user._id,data,updatedAt:now},$setOnInsert:{createdAt:now}},{upsert:true});return reply(req,env,200,{ok:true,saved:true,updatedAt:now.toISOString()});}
    if(path==="/api/account/load"&&req.method==="GET"){const s=await db.collection("saves").findOne({userId:user._id});return reply(req,env,200,{ok:true,save:s?.data??null,updatedAt:s?.updatedAt??null});}
    if(path==="/api/leaderboard"&&req.method==="GET"){const docs=await db.collection("saves").find({},{projection:{userId:1,"data.level":1,"data.nivel":1,"data.xp":1,"data.name":1,"data.nome":1}}).limit(100).toArray(),ids=docs.map(d=>d.userId),users=await db.collection("users").find({_id:{$in:ids}},{projection:{username:1}}).toArray(),names=new Map(users.map(u=>[String(u._id),u.username]));const rows=docs.map(d=>({username:names.get(String(d.userId))||"shinobi",name:d.data?.name??d.data?.nome??null,level:Number(d.data?.level??d.data?.nivel??0),xp:Number(d.data?.xp??0)})).sort((a,b)=>b.level-a.level||b.xp-a.xp).slice(0,50);return reply(req,env,200,{ok:true,leaderboard:rows});}
    if(path==="/api/friends"&&req.method==="GET"){const links=await db.collection("friends").find({ownerId:user._id}).toArray(),ids=links.map(x=>x.friendId),us=ids.length?await db.collection("users").find({_id:{$in:ids}},{projection:{username:1}}).toArray():[];return reply(req,env,200,{ok:true,friends:us.map(x=>safeUser(x))});}
    if(path==="/api/friends/add"&&req.method==="POST"){const b=await bodyJson(req),target=await db.collection("users").findOne({usernameLower:norm(b.username).toLowerCase()});if(!target)return reply(req,env,404,{ok:false,error:"USER_NOT_FOUND"});if(String(target._id)===String(user._id))return reply(req,env,400,{ok:false,error:"SELF_FRIEND"});await db.collection("friends").updateOne({ownerId:user._id,friendId:target._id},{$setOnInsert:{createdAt:new Date()}},{upsert:true});return reply(req,env,200,{ok:true,friend:safeUser(target)});}
    if(path==="/api/online/action"&&req.method==="POST"){const b=await bodyJson(req),now=new Date();await db.collection("online_actions").insertOne({mode:"online",userId:user._id,action:b.action??b,createdAt:now});return reply(req,env,200,{ok:true,accepted:true,serverTime:now.toISOString()});}
    if(path==="/api/online/state"&&req.method==="GET"){const recent=await db.collection("online_actions").find({mode:"online"}).sort({createdAt:-1}).limit(30).toArray();return reply(req,env,200,{ok:true,state:{recent:recent.reverse().map(x=>({userId:String(x.userId),action:x.action,createdAt:x.createdAt}))}});}
    if(path.startsWith("/api/pvp/"))return roomRoute(req,env,db,user,"pvp",path);
    if(path.startsWith("/api/coop/"))return roomRoute(req,env,db,user,"coop",path);
    return reply(req,env,404,{ok:false,error:"ROUTE_NOT_FOUND",path});
  }catch(e){console.error("R41_API_ERROR",e);return reply(req,env,500,{ok:false,error:"INTERNAL_ERROR"});}
  finally{try{await client.close();}catch{}}
}};
