import { DurableObject } from "cloudflare:workers";
import { MongoClient, ObjectId } from "mongodb";

const enc = new TextEncoder();
const dec = new TextDecoder();
const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };
const BUILD = "R41-CLOUDFLARE-MONGODB-INTEGRAL-20260819";
const TOKEN_MS = 30 * 24 * 60 * 60 * 1000;
let sharedClient = null;
let sharedUri = "";
let indexesPromise = null;

function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function unb64url(s){s=String(s||"").replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
async function hmac(secret,data){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(data)));}
function timingSafe(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function hashPassword(password,salt,iterations=210000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return b64url(new Uint8Array(bits));}
function randomBytes(n=16){const a=new Uint8Array(n);crypto.getRandomValues(a);return a;}
function randomSecret(n=24){return b64url(randomBytes(n));}
function norm(v){return String(v??"").trim();}
function cleanText(v,max=120){return norm(v).slice(0,max);}
function bearer(req){const h=req.headers.get("authorization")||"";return /^Bearer\s+/i.test(h)?h.replace(/^Bearer\s+/i,"").trim():"";}
function plainId(x){return x == null ? null : String(x);}
function safeAccount(u){return {id:plainId(u._id),username:u.username,displayName:u.displayName||u.username,role:u.role||"player",createdAt:u.createdAt};}
function cors(req,env){const origin=req.headers.get("origin")||"";const configured=String(env.ALLOWED_ORIGINS||env.ALLOWED_ORIGIN||"https://kaalflash12.github.io").split(",").map(x=>x.trim()).filter(Boolean);const allowed=[...new Set([...configured,"http://localhost:8000","http://127.0.0.1:8000","http://localhost:8787","http://127.0.0.1:8787"])];const selected=allowed.includes(origin)?origin:(!origin?allowed[0]:"null");return{"access-control-allow-origin":selected,"access-control-allow-methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","access-control-allow-headers":"authorization,content-type,x-r41-revision","access-control-expose-headers":"x-r41-revision","access-control-max-age":"86400","cache-control":"no-store","vary":"origin"};}
function reply(req,env,status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...cors(req,env),...extra}});}
async function bodyJson(req){try{return await req.json();}catch{return{};}}
function toObjectId(v){try{return new ObjectId(String(v));}catch{return null;}}
function nowIso(){return new Date().toISOString();}
function roomId(){return `room-${crypto.randomUUID()}`;}

async function mongo(env){
  if(!env.MONGODB_URI)throw new Error("MONGODB_URI_MISSING");
  if(!sharedClient || sharedUri!==env.MONGODB_URI){sharedUri=env.MONGODB_URI;sharedClient=new MongoClient(env.MONGODB_URI,{maxPoolSize:6,minPoolSize:0,maxIdleTimeMS:45000,serverSelectionTimeoutMS:6000,connectTimeoutMS:6000});await sharedClient.connect();indexesPromise=null;}
  return sharedClient.db(env.MONGODB_DB||"naruto_shinobi_r41");
}
async function ensureIndexes(db){
  if(!indexesPromise) indexesPromise=Promise.all([
    db.collection("users").createIndex({usernameLower:1},{unique:true,name:"uq_username"}),
    db.collection("sessions").createIndex({sid:1},{unique:true,name:"uq_session"}),
    db.collection("sessions").createIndex({expiresAt:1},{expireAfterSeconds:0,name:"ttl_session"}),
    db.collection("saves").createIndex({userId:1,slotId:1},{unique:true,name:"uq_save_slot"}),
    db.collection("saves").createIndex({"data.playerId":1},{name:"ix_save_player"}),
    db.collection("friends").createIndex({ownerId:1,friendId:1},{unique:true,name:"uq_friend"}),
    db.collection("room_registry").createIndex({roomId:1},{unique:true,name:"uq_room_id"}),
    db.collection("room_registry").createIndex({updatedAt:-1},{name:"ix_room_updated"}),
    db.collection("world_events").createIndex({campaignId:1,createdAt:-1},{name:"ix_world_event"}),
    db.collection("world_state").createIndex({campaignId:1},{unique:true,name:"uq_world_campaign"}),
    db.collection("audit_events").createIndex({createdAt:-1},{name:"ix_audit_time"}),
    db.collection("recovery_codes").createIndex({userId:1},{name:"ix_recovery_user"})
  ]).catch(e=>{indexesPromise=null;throw e;});
  return indexesPromise;
}
async function issueToken(env,db,user){const sid=crypto.randomUUID(),expiresAt=new Date(Date.now()+TOKEN_MS),payload=b64url(enc.encode(JSON.stringify({sub:plainId(user._id),usr:user.username,sid,exp:expiresAt.getTime()}))),sig=b64url(await hmac(env.AUTH_SECRET,payload));await db.collection("sessions").insertOne({sid,userId:user._id,createdAt:new Date(),expiresAt,revoked:false});return `${payload}.${sig}`;}
async function verifyToken(env,db,token){if(!token||!token.includes("."))return null;const [p,s]=token.split(".",2),expected=b64url(await hmac(env.AUTH_SECRET,p));if(!timingSafe(s,expected))return null;try{const data=JSON.parse(dec.decode(unb64url(p)));if(!data.exp||data.exp<Date.now()||!data.sid)return null;const session=await db.collection("sessions").findOne({sid:data.sid,revoked:{$ne:true},expiresAt:{$gt:new Date()}});if(!session)return null;const oid=toObjectId(data.sub);return oid?await db.collection("users").findOne({_id:oid}):null;}catch{return null;}}
async function requireUser(req,env,db){return verifyToken(env,db,bearer(req));}
async function revokeCurrent(req,env,db){const token=bearer(req);if(!token)return;try{const [p]=token.split(".",1),data=JSON.parse(dec.decode(unb64url(p)));if(data.sid)await db.collection("sessions").updateOne({sid:data.sid},{$set:{revoked:true,revokedAt:new Date()}});}catch{}}
function slotSummary(s){const c=s?.data?.character||{};return {slotId:s.slotId,name:c.name||c.nome||"Personagem",level:Number(c.level||c.nivel||1),graduation:c.graduation||c.graduacao||"",avatar:c.avatar||c.portrait||"",updatedAt:s.updatedAt||null,gameVersion:s.gameVersion||""};}
function clampSaveForStorage(save){if(!save||typeof save!=="object"||Array.isArray(save))throw new Error("SAVE_INVALID");const raw=JSON.stringify(save);if(raw.length>3_500_000)throw new Error("SAVE_TOO_LARGE");return save;}
async function audit(db,type,userId,detail={}){try{await db.collection("audit_events").insertOne({type,userId:userId||null,detail,createdAt:new Date(),build:BUILD});}catch{}}

export class GameRoom extends DurableObject {
  constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;}
  async read(){return (await this.ctx.storage.get("room"))||null;}
  async write(room){room.updatedAt=nowIso();await this.ctx.storage.put("room",room);return room;}
  liveMembers(room){const cutoff=Date.now()-120000;return Object.values(room?.members||{}).filter(m=>Date.parse(m.lastSeen||0)>=cutoff);}
  async fetch(req){const u=new URL(req.url),action=u.pathname.replace(/^\/+/,"");let room=await this.read(),b={};if(req.method!=="GET")try{b=await req.json();}catch{}
    if(action==="create"){if(room)return new Response(JSON.stringify({ok:false,error:"ROOM_ALREADY_EXISTS"}),{status:409});room={roomId:b.roomId,title:cleanText(b.title||"Campanha Online",80),campaignId:cleanText(b.campaignId,100),mode:b.mode||"online",ownerUserId:b.userId,members:{},messages:[],actions:[],nextMessageId:1,createdAt:nowIso(),updatedAt:nowIso()};room.members[b.userId]={userId:b.userId,playerId:b.playerId,character:b.character||{},role:"host",joinedAt:nowIso(),lastSeen:nowIso()};await this.write(room);return Response.json({ok:true,roomId:room.roomId,title:room.title,campaignId:room.campaignId,room,members:this.liveMembers(room)});}
    if(!room)return new Response(JSON.stringify({ok:false,error:"ROOM_NOT_FOUND"}),{status:404,headers:JSON_HEADERS});
    if(action==="join"){room.members[b.userId]={...(room.members[b.userId]||{}),userId:b.userId,playerId:b.playerId,character:b.character||{},role:room.ownerUserId===b.userId?"host":"member",joinedAt:room.members[b.userId]?.joinedAt||nowIso(),lastSeen:nowIso()};await this.write(room);return Response.json({ok:true,roomId:room.roomId,title:room.title,campaignId:room.campaignId,room,members:this.liveMembers(room)});}
    if(action==="heartbeat"){if(!room.members[b.userId])room.members[b.userId]={userId:b.userId,playerId:b.playerId,joinedAt:nowIso(),role:"member"};room.members[b.userId].lastSeen=nowIso();if(b.character)room.members[b.userId].character=b.character;await this.write(room);return Response.json({ok:true,serverTime:nowIso()});}
    if(action==="room"){return Response.json({ok:true,room:{roomId:room.roomId,title:room.title,campaignId:room.campaignId,mode:room.mode,ownerUserId:room.ownerUserId,createdAt:room.createdAt,updatedAt:room.updatedAt},members:this.liveMembers(room)});}
    if(action==="message"){const message=cleanText(b.message,1000);if(!message)return new Response(JSON.stringify({ok:false,error:"MESSAGE_EMPTY"}),{status:400,headers:JSON_HEADERS});const m={id:room.nextMessageId++,userId:b.userId,playerId:b.playerId||"",characterName:cleanText(b.characterName||"Shinobi",80),message,createdAt:nowIso()};room.messages.push(m);room.messages=room.messages.slice(-250);await this.write(room);return Response.json({ok:true,message:m});}
    if(action==="messages"){const after=Number(u.searchParams.get("afterId")||b.afterId||0);return Response.json({ok:true,messages:room.messages.filter(x=>Number(x.id)>after).slice(-250)});}
    if(action==="action"){const envelope=b.action??b;const type=cleanText(envelope?.type||envelope?.action||"action",80);const forbidden=/grant|award|give.?xp|set.?level|admin/i.test(type);if(forbidden)return new Response(JSON.stringify({ok:false,error:"CLIENT_AUTHORITY_FORBIDDEN"}),{status:400,headers:JSON_HEADERS});const ev={id:crypto.randomUUID(),userId:b.userId,playerId:b.playerId||"",type,payload:envelope,createdAt:nowIso()};room.actions.push(ev);room.actions=room.actions.slice(-200);await this.write(room);return Response.json({ok:true,accepted:true,event:ev,serverTime:nowIso()});}
    if(action==="state"){return Response.json({ok:true,state:{room:{roomId:room.roomId,title:room.title,campaignId:room.campaignId,mode:room.mode},members:this.liveMembers(room),messages:room.messages.slice(-100),actions:room.actions.slice(-100)}});}
    return new Response(JSON.stringify({ok:false,error:"ROOM_ROUTE_NOT_FOUND"}),{status:404,headers:JSON_HEADERS});
  }
}

async function roomCall(env,id,action,payload={},method="POST",query=""){const stub=env.GAME_ROOMS.getByName(id);const url=`https://room.internal/${action}${query}`;return stub.fetch(url,{method,headers:{"content-type":"application/json"},body:method==="GET"?undefined:JSON.stringify(payload)});}
async function roomJson(env,id,action,payload={},query=""){const r=await roomCall(env,id,action,payload,"POST",query),d=await r.json().catch(()=>({}));return {status:r.status,data:d};}

async function aiRoute(req,env){if(!env.AI)return reply(req,env,503,{ok:false,error:"WORKERS_AI_NOT_BOUND"});const b=await bodyJson(req);const facts=b?.gameContext?.facts||b?.facts||[],rules=b?.gameContext?.rules||"TERION 2D10 resolve resultados mecânicos antes da narrativa.";const system=`Você é o narrador do Shinobi no Sho. TERION é a autoridade mecânica. Nunca invente sucesso, dano, recompensa, técnica desbloqueada, morte ou relação que não esteja nos fatos confirmados. Narre consequência de fatos confirmados e ofereça ações possíveis. ${rules}`;const prompt=JSON.stringify({mode:b.mode||"game_master",intent:b.intent||b.action||b.text||"continuar",facts,director:b.director||{},context:b.gameContext||b.context||{} }).slice(0,45000);const result=await env.AI.run("@cf/meta/llama-3.2-1b-instruct",{messages:[{role:"system",content:system},{role:"user",content:prompt}]});const text=result?.response||result?.result?.response||result?.text||JSON.stringify(result);return reply(req,env,200,{ok:true,result:text,provider:"cloudflare-workers-ai",model:"@cf/meta/llama-3.2-1b-instruct",role:b.mode||"game_master"});}

export default {async fetch(req,env){
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req,env)});
  const url=new URL(req.url),path=url.pathname.replace(/\/+$/g,"")||"/";
  if(path==="/"||path==="/api/status")return reply(req,env,200,{ok:true,service:"naruto-shinobi-r41-api",build:BUILD,enabled:!!env.AI,provider:env.AI?"cloudflare-workers-ai":"offline",model:env.AI?"@cf/meta/llama-3.2-1b-instruct":"gerador local",envFound:!!env.AI,cloudSave:!!env.MONGODB_URI,memory:!!env.MONGODB_URI,rulesDatabase:true,onlineRooms:!!env.GAME_ROOMS,providers:[{id:"workers-ai",enabled:!!env.AI}],routes:{auth:true,save:true,online:true,pvp:true,coop:true,world:true,ai:!!env.AI},storage:"mongodb-atlas",realtime:"cloudflare-durable-objects",configured:!!(env.MONGODB_URI&&env.AUTH_SECRET&&env.GAME_ROOMS)});
  if(!env.MONGODB_URI||!env.AUTH_SECRET)return reply(req,env,503,{ok:false,error:"SERVER_NOT_CONFIGURED",missing:[!env.MONGODB_URI?"MONGODB_URI":null,!env.AUTH_SECRET?"AUTH_SECRET":null].filter(Boolean)});
  let db;
  try{db=await mongo(env);await ensureIndexes(db);}catch(e){console.error("MONGO_CONNECT",e);return reply(req,env,503,{ok:false,error:"DATABASE_UNAVAILABLE"});}
  try{
    if(path==="/api/auth/register"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),password=String(b.password||""),displayName=cleanText(b.displayName||username,60);if(!/^[\p{L}\p{N}_.-]{3,32}$/u.test(username)||password.length<8||password.length>200)return reply(req,env,400,{ok:false,error:"INVALID_CREDENTIALS_FORMAT"});const salt=randomBytes(),passHash=await hashPassword(password,salt),now=new Date(),role="player";let r;try{r=await db.collection("users").insertOne({username,usernameLower:username.toLowerCase(),displayName,role,passSalt:b64url(salt),passHash,passIter:210000,createdAt:now,updatedAt:now});}catch(e){if(e?.code===11000)return reply(req,env,409,{ok:false,error:"USERNAME_EXISTS"});throw e;}const user={_id:r.insertedId,username,displayName,role,createdAt:now},token=await issueToken(env,db,user),recoveryCode=randomSecret(18),recoverySalt=randomBytes(),recoveryHash=await hashPassword(recoveryCode,recoverySalt,120000);await db.collection("recovery_codes").insertOne({userId:r.insertedId,hash:recoveryHash,salt:b64url(recoverySalt),iterations:120000,used:false,createdAt:now});await audit(db,"auth.register",r.insertedId,{username});return reply(req,env,201,{ok:true,token,account:safeAccount(user),recoveryCode,mirrors:{cloud:true,mongodb:true,drive:false}});}
    if(path==="/api/auth/login"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),password=String(b.password||""),u=await db.collection("users").findOne({usernameLower:username.toLowerCase()});if(!u)return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});const got=await hashPassword(password,unb64url(u.passSalt),u.passIter||210000);if(!timingSafe(got,u.passHash))return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});const token=await issueToken(env,db,u);await audit(db,"auth.login",u._id,{});return reply(req,env,200,{ok:true,token,account:safeAccount(u),mirrors:{cloud:true,mongodb:true,drive:false}});}
    if(path==="/api/auth/recover"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),code=String(b.recoveryCode||""),newPassword=String(b.newPassword||"");if(newPassword.length<8)return reply(req,env,400,{ok:false,error:"PASSWORD_TOO_SHORT"});const u=await db.collection("users").findOne({usernameLower:username.toLowerCase()});if(!u)return reply(req,env,401,{ok:false,error:"RECOVERY_INVALID"});const docs=await db.collection("recovery_codes").find({userId:u._id,used:{$ne:true}}).sort({createdAt:-1}).limit(10).toArray();let match=null;for(const rc of docs){const got=await hashPassword(code,unb64url(rc.salt),rc.iterations||120000);if(timingSafe(got,rc.hash)){match=rc;break;}}if(!match)return reply(req,env,401,{ok:false,error:"RECOVERY_INVALID"});const salt=randomBytes(),passHash=await hashPassword(newPassword,salt);await db.collection("users").updateOne({_id:u._id},{$set:{passSalt:b64url(salt),passHash,passIter:210000,updatedAt:new Date()}});await db.collection("recovery_codes").updateOne({_id:match._id},{$set:{used:true,usedAt:new Date()}});await db.collection("sessions").updateMany({userId:u._id},{$set:{revoked:true,revokedAt:new Date()}});return reply(req,env,200,{ok:true,recovered:true});}
    if(path==="/api/ai"&&req.method==="POST")return aiRoute(req,env);
    if(path==="/api/v84/bootstrap"){const user=await requireUser(req,env,db);const campaignId=user?cleanText((await bodyJson(req)).campaignId,120):"public";const ws=campaignId&&campaignId!=="public"?await db.collection("world_state").findOne({campaignId}):null;return reply(req,env,200,{ok:true,world:ws?.world||{npcs:[],arcs:[],missions:[],locations:[]},serverTime:nowIso(),build:BUILD});}

    const user=await requireUser(req,env,db);
    if(path==="/api/auth/me")return user?reply(req,env,200,{ok:true,account:safeAccount(user),mirrors:{cloud:true,mongodb:true}}):reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
    if(!user)return reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
    if(path==="/api/auth/logout"){await revokeCurrent(req,env,db);return reply(req,env,200,{ok:true});}

    if(path==="/api/account/slots"){const docs=await db.collection("saves").find({userId:user._id}).sort({updatedAt:-1}).toArray();return reply(req,env,200,{ok:true,slots:docs.map(slotSummary),mirrors:{cloud:true,mongodb:true,drive:false}});}
    if(path==="/api/account/save"&&["POST","PUT"].includes(req.method)){const b=await bodyJson(req),slotId=cleanText(b.slotId||"slot-principal",100),data=clampSaveForStorage(b.save??b.data),gameVersion=cleanText(b.gameVersion||data?.version||"R41",80),now=new Date(),prior=await db.collection("saves").findOne({userId:user._id,slotId}),revision=Number(prior?.revision||0)+1;await db.collection("saves").updateOne({userId:user._id,slotId},{$set:{data,gameVersion,revision,updatedAt:now},$setOnInsert:{userId:user._id,slotId,createdAt:now}},{upsert:true});await audit(db,"save.write",user._id,{slotId,revision,gameVersion});return reply(req,env,200,{ok:true,saved:true,slotId,revision,updatedAt:now.toISOString(),mirrors:{cloud:true,mongodb:true,drive:false}} ,{"x-r41-revision":String(revision)});}
    if(path==="/api/account/load"){const b=await bodyJson(req),slotId=cleanText(b.slotId||"slot-principal",100),s=await db.collection("saves").findOne({userId:user._id,slotId});if(!s)return reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND",slotId});return reply(req,env,200,{ok:true,save:s.data,slotId:s.slotId,revision:s.revision||0,updatedAt:s.updatedAt,mirrors:{cloud:true,mongodb:true,drive:false}},{"x-r41-revision":String(s.revision||0)});}
    if(path==="/api/account/delete"){const b=await bodyJson(req),slotId=cleanText(b.slotId,100);if(!slotId)return reply(req,env,400,{ok:false,error:"SLOT_REQUIRED"});const r=await db.collection("saves").deleteOne({userId:user._id,slotId});return reply(req,env,200,{ok:true,deleted:r.deletedCount===1,slotId});}
    if(path==="/api/cloud/load"){const b=await bodyJson(req),playerId=cleanText(b.playerId,180);const s=await db.collection("saves").findOne({userId:user._id,...(playerId?{"data.playerId":playerId}:{})},{sort:{updatedAt:-1}});if(!s)return reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND"});return reply(req,env,200,{ok:true,save:s.data,playerId:s.data?.playerId||playerId,campaignId:s.data?.campaignId||"",updatedAt:s.updatedAt});}

    if(path==="/api/private/unlock"){const b=await bodyJson(req);const allowed=user.role==="leon"||(env.LEON_PRIVATE_CODE&&timingSafe(String(b.code||""),String(env.LEON_PRIVATE_CODE)));if(!allowed)return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});return reply(req,env,200,{ok:true,session:bearer(req)||"account-session"});}
    if(path==="/api/private/leon/load"){if(user.role!=="leon")return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});const s=await db.collection("saves").findOne({userId:user._id,slotId:"leon-private"});return s?reply(req,env,200,{ok:true,save:s.data,updatedAt:s.updatedAt}):reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND"});}
    if(path==="/api/private/leon/save"){if(user.role!=="leon")return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});const b=await bodyJson(req),data=clampSaveForStorage(b.save),now=new Date(),prior=await db.collection("saves").findOne({userId:user._id,slotId:"leon-private"}),revision=Number(prior?.revision||0)+1;await db.collection("saves").updateOne({userId:user._id,slotId:"leon-private"},{$set:{data,gameVersion:cleanText(b.gameVersion||data?.version||"R41",80),revision,updatedAt:now},$setOnInsert:{userId:user._id,slotId:"leon-private",createdAt:now}},{upsert:true});return reply(req,env,200,{ok:true,updatedAt:now.toISOString(),revision,mirrors:{cloud:true,mongodb:true,drive:false}});}

    if(path==="/api/leaderboard"){const docs=await db.collection("saves").find({},{projection:{userId:1,"data.character.name":1,"data.character.level":1,"data.stats.totalXp":1,"data.character.avatar":1}}).limit(300).toArray(),ids=[...new Map(docs.map(d=>[String(d.userId),d.userId])).values()],users=await db.collection("users").find({_id:{$in:ids}},{projection:{username:1,displayName:1}}).toArray(),names=new Map(users.map(u=>[String(u._id),u]));const rows=docs.map(d=>{const u=names.get(String(d.userId));return{username:u?.username||"shinobi",displayName:u?.displayName||u?.username||"Shinobi",name:d.data?.character?.name||null,level:Number(d.data?.character?.level||1),xp:Number(d.data?.stats?.totalXp||0),avatar:d.data?.character?.avatar||""};}).sort((a,b)=>b.level-a.level||b.xp-a.xp).slice(0,50);return reply(req,env,200,{ok:true,leaderboard:rows});}
    if(path==="/api/friends"){const links=await db.collection("friends").find({ownerId:user._id}).toArray(),ids=links.map(x=>x.friendId),us=ids.length?await db.collection("users").find({_id:{$in:ids}}).toArray():[];return reply(req,env,200,{ok:true,friends:us.map(safeAccount)});}
    if(path==="/api/friends/add"){const b=await bodyJson(req),target=await db.collection("users").findOne({usernameLower:cleanText(b.username,32).toLowerCase()});if(!target)return reply(req,env,404,{ok:false,error:"USER_NOT_FOUND"});if(String(target._id)===String(user._id))return reply(req,env,400,{ok:false,error:"SELF_FRIEND"});await db.collection("friends").updateOne({ownerId:user._id,friendId:target._id},{$setOnInsert:{createdAt:new Date()}},{upsert:true});return reply(req,env,200,{ok:true,friend:safeAccount(target)});}

    if(path==="/api/online/create"){const b=await bodyJson(req),id=roomId(),payload={...b,roomId:id,userId:plainId(user._id),mode:"online"},r=await roomJson(env,id,"create",payload);if(r.status<300)await db.collection("room_registry").updateOne({roomId:id},{$set:{roomId:id,title:r.data.title||cleanText(b.title,80),campaignId:r.data.campaignId||cleanText(b.campaignId,100),ownerUserId:user._id,mode:"online",updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{upsert:true});return reply(req,env,r.status,r.data);}
    if(path==="/api/online/join"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"join",{...b,userId:plainId(user._id)});if(r.status<300)await db.collection("room_registry").updateOne({roomId:id},{$set:{updatedAt:new Date()}},{upsert:true});return reply(req,env,r.status,r.data);}
    if(path==="/api/online/heartbeat"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"heartbeat",{...b,userId:plainId(user._id)});return reply(req,env,r.status,r.data);}
    if(path==="/api/online/room"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"room",{userId:plainId(user._id)});return reply(req,env,r.status,r.data);}
    if(path==="/api/online/message"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"message",{...b,userId:plainId(user._id)});return reply(req,env,r.status,r.data);}
    if(path==="/api/online/messages"){const b=await bodyJson(req),id=cleanText(b.roomId,120),afterId=Number(b.afterId||0);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"messages",{userId:plainId(user._id),afterId},`?afterId=${encodeURIComponent(afterId)}`);return reply(req,env,r.status,r.data);}
    if(path==="/api/online/action"){const b=await bodyJson(req),id=cleanText(b.roomId||b.room?.roomId,120);if(id){const r=await roomJson(env,id,"action",{...b,userId:plainId(user._id)});return reply(req,env,r.status,r.data);}await db.collection("audit_events").insertOne({type:"online.action.unroomed",userId:user._id,detail:b,createdAt:new Date()});return reply(req,env,200,{ok:true,accepted:true,serverTime:nowIso()});}
    if(path==="/api/online/state"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,200,{ok:true,state:{rooms:await db.collection("room_registry").find({}).sort({updatedAt:-1}).limit(20).toArray()}});const r=await roomJson(env,id,"state",{userId:plainId(user._id)});return reply(req,env,r.status,r.data);}

    if(/^\/api\/(pvp|coop)\//.test(path)){const [,mode,action]=path.match(/^\/api\/(pvp|coop)\/([^/]+)$/)||[];const b=await bodyJson(req);if(!mode)return reply(req,env,404,{ok:false,error:"ROUTE_NOT_FOUND"});if(action==="create"){const id=roomId(),r=await roomJson(env,id,"create",{...b,roomId:id,userId:plainId(user._id),mode});return reply(req,env,r.status,r.data);}const id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const mapped=action==="join"?"join":action==="state"?"state":action==="action"?"action":action;const r=await roomJson(env,id,mapped,{...b,userId:plainId(user._id)});return reply(req,env,r.status,r.data);}

    if(path==="/api/v84/world/event"){const b=await bodyJson(req),campaignId=cleanText(b.campaignId||b.detail?.campaignId||"default",120),event={type:cleanText(b.type||"event",120),detail:b.detail||{},minutes:Number(b.minutes||0),source:cleanText(b.source||"r41",120),userId:user._id,campaignId,createdAt:new Date()};await db.collection("world_events").insertOne(event);return reply(req,env,200,{ok:true,event:{...event,_id:undefined,userId:plainId(user._id),at:event.createdAt.toISOString()}});}
    if(path==="/api/v84/world/savepoint"){const b=await bodyJson(req),campaignId=cleanText(b.campaignId||"default",120),now=new Date();await db.collection("world_state").updateOne({campaignId},{$set:{lastSavePoint:{label:cleanText(b.label,180),changes:Array.isArray(b.changes)?b.changes.slice(-100):[],character:b.character||null,at:now},updatedAt:now},$setOnInsert:{campaignId,createdAt:now}},{upsert:true});return reply(req,env,200,{ok:true,savePoint:{label:b.label,at:now.toISOString()}});}

    return reply(req,env,404,{ok:false,error:"ROUTE_NOT_FOUND",path});
  }catch(e){console.error("R41_API_ERROR",e);const msg=String(e?.message||e);return reply(req,env,msg==="SAVE_TOO_LARGE"?413:500,{ok:false,error:msg.startsWith("SAVE_")?msg:"INTERNAL_ERROR"});}
}};
