alter table public.ranked_profiles enable row level security;
alter table public.ranked_queue enable row level security;
alter table public.ranked_matches enable row level security;
alter table public.ranked_turn_submissions enable row level security;
alter table public.battle_replays enable row level security;
alter table public.event_templates enable row level security;
alter table public.admin_principals enable row level security;
alter table public.admin_roles enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_principal_roles enable row level security;
alter table public.admin_role_permissions enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.admin_bootstrap enable row level security;
alter table public.ai_director_runs enable row level security;
alter table public.ai_event_proposals enable row level security;

revoke all privileges on table public.ranked_profiles from anon, authenticated;
revoke all privileges on table public.ranked_queue from anon, authenticated;
revoke all privileges on table public.ranked_matches from anon, authenticated;
revoke all privileges on table public.ranked_turn_submissions from anon, authenticated;
revoke all privileges on table public.battle_replays from anon, authenticated;
revoke all privileges on table public.event_templates from anon, authenticated;
revoke all privileges on table public.admin_principals from anon, authenticated;
revoke all privileges on table public.admin_roles from anon, authenticated;
revoke all privileges on table public.admin_permissions from anon, authenticated;
revoke all privileges on table public.admin_principal_roles from anon, authenticated;
revoke all privileges on table public.admin_role_permissions from anon, authenticated;
revoke all privileges on table public.admin_audit_log from anon, authenticated;
revoke all privileges on table public.admin_bootstrap from anon, authenticated;
revoke all privileges on table public.ai_director_runs from anon, authenticated;
revoke all privileges on table public.ai_event_proposals from anon, authenticated;
