alter policy achievement_progress_self on public.achievement_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy economy_ledger_self on public.economy_ledger using (user_id = (select auth.uid()));
alter policy event_progress_self on public.event_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy mastery_match_credits_self on public.mastery_match_credits using (user_id = (select auth.uid()));
alter policy mastery_progress_self on public.mastery_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy mission_attempts_self on public.mission_attempts using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy mission_progress_self on public.mission_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy player_equipment_self on public.player_equipment using (user_id = (select auth.uid()));
alter policy player_equipment_slots_self on public.player_equipment_slots using (user_id = (select auth.uid()));
alter policy player_items_self on public.player_items using (user_id = (select auth.uid()));
alter policy player_loadout_slots_self on public.player_loadout_slots using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy saves_self_select on public.player_save_snapshots using (user_id = (select auth.uid()));
alter policy settings_self_all on public.player_settings using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy player_techniques_self on public.player_techniques using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy player_unlocks_self on public.player_unlocks using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy profiles_self_select on public.profiles using (user_id = (select auth.uid()));
alter policy profiles_self_update on public.profiles using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy pve_daily_self on public.pve_daily using (user_id = (select auth.uid()));
alter policy raid_attempt_self on public.raid_attempts using (user_id = (select auth.uid()));
alter policy raid_turn_self_read on public.raid_turn_submissions using (exists (select 1 from public.raid_attempts a where a.id = raid_turn_submissions.attempt_id and a.user_id = (select auth.uid())));
alter policy reward_claims_self on public.reward_claims using (user_id = (select auth.uid()));
alter policy story_progress_self on public.story_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
alter policy task_progress_self on public.task_progress using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
