import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const URL=Deno.env.get("SUPABASE_URL")!;
const BODY_MAX=1024*1024,ID_MAX=160,MSG_MAX=500,DELTA_MAX=1_000_000_000;
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const C={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, x-client-info, apikey, content-type","access-control-allow-methods":"GET,POST,PATCH,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
function pick(name:string,legacy:string){const raw=Deno.env.get(name);if(raw){try{const o=JSON.parse(raw);return String(o.default??Object.values(o)[0]??"")}catch{return raw}}return Deno.env.get(legacy)??""}
const PUB=pick("SUPABASE_PUBLISHABLE_KEYS","SUPABASE_ANON_KEY"),SECRET=pick("SUPABASE_SECRET_KEYS","SUPABASE_SERVICE_ROLE_KEY");
const admin=()=>createClient(URL,SECRET,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const J=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:C});
class AppError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code}}
async function user(req:Request){const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))throw new AppError(401,"AUTH","Sessão inválida.");const c=createClient(URL,PUB,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const {data,error}=await c.auth.getUser();if(error||!data.user)throw new AppError(401,"AUTH","Sessão inválida.");return data.user}
async function body(req:Request){const declared=Number(req.headers.get("content-length")||"0");if(Number.isFinite(declared)&&declared>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");const raw=await req.arrayBuffer();if(raw.byteLength>BODY_MAX)throw new AppError(413,"BODY_TOO_LARGE","Corpo da requisição excede o limite.");if(!raw.byteLength)return{} as Record<string,any>;try{const v=JSON.parse(new TextDecoder().decode(raw));if(!v||typeof v!=="object"||Array.isArray(v))throw 0;return v as Record<string,any>}catch{throw new AppError(400,"INVALID_JSON","JSON inválido.")}}
function route(req:Request){const p=new URL(req.url).pathname;return p.replace(/^.*\/admin/,"")||"/"}
function txt(v:unknown,max=ID_MAX){const s=String(v??"").trim();if(!s||s.length>max||/[\u0000-\u001f\u007f]/.test(s))throw new AppError(400,"INPUT","Campo inválido.");return s}
function uuid(v:unknown){const s=String(v||"");if(!UUID_RE.test(s))throw new AppError(400,"ID","Identificador inválido.");return s}
function delta(v:unknown){const n=Number(v);if(!Number.isFinite(n)||!Number.isSafeInteger(n)||Math.abs(n)>DELTA_MAX)throw new AppError(400,"DELTA","Delta inválido.");return n}
async function principalFor(db:any,userId:string){const p=await db.from("admin_principals").select("id,display_name,active").eq("user_id",userId).eq("active",true).maybeSingle();if(p.error)throw p.error;if(!p.data)return null;const rr=await db.from("admin_principal_roles").select("role").eq("principal_id",p.data.id);if(rr.error)throw rr.error;return{...p.data,roles:(rr.data||[]).map((x:any)=>String(x.role)).filter(Boolean)}}
async function permission(req:Request,db:any,perm:string){const u=await user(req),p=await principalFor(db,u.id);if(!p)throw new AppError(403,"PERMISSION","Principal administrativo inativo ou ausente.");if(!p.roles.length)throw new AppError(403,"PERMISSION","Nenhuma função administrativa atribuída.");const pr=await db.from("admin_role_permissions").select("role,permission").in("role",p.roles).eq("permission",perm).limit(1);if(pr.error)throw pr.error;if(!(pr.data||[]).length)throw new AppError(403,"PERMISSION","Permissão insuficiente.");return u}
async function audit(db:any,x:{principalId?:string,action:string,targetType?:string,targetId?:string,before?:unknown,after?:unknown}){const {error}=await db.from("admin_audit_log").insert({principal_id:x.principalId??null,action:x.action,target_type:x.targetType??null,target_id:x.targetId??null,before:x.before??null,after:x.after??null});if(error)throw error}
const REF_RULES:Record<string,Array<[string,string,boolean?]>>={character:[["baseTechniqueIds","technique",true]],technique:[["characterId","character"],["parentTechniqueId","technique"],["lineageId","technique_lineage"],["masteryId","mastery"],["animationProfileId","animation_profile"]],technique_lineage:[["characterId","character"],["rootTechniqueId","technique"]],mastery:[["characterId","character"],["techniqueId","technique"],["unlockRequirements.relatedTechnique.techniqueId","technique"]],mission:[["sceneId","scene"]],story_chapter:[["sceneId","scene"]],equipment:[["animationProfileId","animation_profile"]],boss:[["aiProfileId","ai_profile"],["sceneId","scene"],["characterId","character"],["techniqueIds","technique",true]],event:[["bossId","boss"],["missionIds","mission",true]]};
const at=(o:any,p:string)=>p.split(".").reduce((v,k)=>v?.[k],o);
async function refs(db:any,type:string,payload:any){const errors:string[]=[];for(const [field,target,array] of REF_RULES[type]||[]){const raw=at(payload,field),vals=array?(Array.isArray(raw)?raw:raw==null?[]:[raw]):[raw],ids=[...new Set(vals.filter((x:any)=>x!=null&&String(x)!=="").map(String))];if(!ids.length)continue;if(ids.some((x:string)=>x.length>ID_MAX))throw new AppError(400,"REFERENCES","Referência inválida.");const {data,error}=await db.from("content_entities").select("entity_id").eq("entity_type",target).in("entity_id",ids).not("published","is",null);if(error)throw error;const found=new Set((data||[]).map((x:any)=>x.entity_id));for(const id of ids)if(!found.has(id))errors.push(`${type}:${payload?.id||"?"} ${field} -> ${target}:${id} ausente/não publicado`)}return errors}
function contentInput(b:any){const type=txt(b.type,64),payload=b.payload;if(!payload||typeof payload!=="object"||Array.isArray(payload))throw new AppError(400,"PAYLOAD","Payload inválido.");if(payload.id!=null)txt(payload.id,ID_MAX);return{type,payload}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:C});try{if(!["GET","POST","PATCH"].includes(req.method))return J({ok:false,code:"METHOD",error:"Método inválido."},405);const r=route(req),db=admin();
  if(r==="/bootstrap")return J({ok:false,code:"BOOTSTRAP_CLOSED",error:"Bootstrap administrativo encerrado."},410);
  if(r==="/status"){if(req.method!=="GET")throw new AppError(405,"METHOD","Método inválido.");const u=await user(req),p=await principalFor(db,u.id),{data:pub,error:pe}=await db.from("content_publications").select("revision").order("revision",{ascending:false}).limit(1).maybeSingle();if(pe)throw pe;const {count,error:ee}=await db.from("event_instances").select("id",{head:true,count:"exact"}).eq("status","ACTIVE");if(ee)throw ee;return J({ok:true,allowed:!!p,role:p?.roles?.[0]||"PLAYER",bootstrapAvailable:false,contentRevision:pub?.revision||0,activeEvents:count||0})}
  if(r==="/accounts"&&req.method==="GET"){await permission(req,db,"accounts.read");const q=(new URL(req.url).searchParams.get("q")||"").trim().slice(0,80);let query=db.from("profiles").select("user_id,username,level,xp,ryo,rank,banned,ban_reason,created_at").order("created_at",{ascending:false}).limit(200);if(q)query=query.ilike("username",`%${q.replace(/[,%()]/g,"")}%`);const {data,error}=await query;if(error)throw error;return J({ok:true,accounts:data||[]})}
  const am=r.match(/^\/accounts\/([^/]+)$/);if(am&&req.method==="PATCH"){const b=await body(req),id=uuid(am[1]),hasR=b.ryoDelta!==undefined,hasX=b.xpDelta!==undefined,hasM=b.toggleBan!==undefined;if(!hasR&&!hasX&&!hasM)throw new AppError(400,"ACCOUNT_PATCH","Nenhuma alteração suportada.");if(hasR||hasX)await permission(req,db,"accounts.economy");if(hasM)await permission(req,db,"accounts.moderate");const actor=await user(req),p=await principalFor(db,actor.id),{data:before,error:be}=await db.from("profiles").select("*").eq("user_id",id).maybeSingle();if(be)throw be;if(!before)throw new AppError(404,"ACCOUNT","Conta ausente.");const patch:any={};if(hasM){if(typeof b.toggleBan!=="boolean")throw new AppError(400,"BAN","toggleBan inválido.");patch.banned=!before.banned;patch.ban_reason=patch.banned?String(b.reason||"").slice(0,300)||null:null}if(hasR)patch.ryo=Math.max(0,Number(before.ryo||0)+delta(b.ryoDelta));if(hasX)patch.xp=Math.max(0,Number(before.xp||0)+delta(b.xpDelta));const {data:after,error}=await db.from("profiles").update(patch).eq("user_id",id).select("*").single();if(error)throw error;await audit(db,{principalId:p?.id,action:"account.update",targetType:"profile",targetId:id,before,after});return J({ok:true,account:after})}
  if(r==="/content/validate"&&req.method==="POST"){await permission(req,db,"content.write");const b=await body(req),{type,payload}=contentInput(b),schema=await db.rpc("content_payload_valid",{p_type:type,p_payload:payload});if(schema.error)throw schema.error;const re=schema.data?await refs(db,type,payload):[];return J({ok:true,valid:!!schema.data&&!re.length,errors:[...(schema.data?[]:[`Payload não corresponde ao schema ${type}`]),...re]})}
  if(r==="/content/publish"&&req.method==="POST"){const actor=await permission(req,db,"content.publish"),p=await principalFor(db,actor.id),b=await body(req),{type,payload}=contentInput(b),id=txt(payload.id,ID_MAX),valid=await db.rpc("content_payload_valid",{p_type:type,p_payload:payload});if(valid.error)throw valid.error;if(!valid.data)throw new AppError(400,"SCHEMA","Payload inválido.");const re=await refs(db,type,payload);if(re.length)throw new AppError(400,"REFERENCES",re.join(" | "));const {data:cur,error:ce}=await db.from("content_entities").select("*").eq("entity_type",type).eq("entity_id",id).maybeSingle();if(ce)throw ce;const version=Number(cur?.published_version||0)+1,message=String(b.message||"").slice(0,MSG_MAX);let e=(await db.from("content_versions").insert({entity_type:type,entity_id:id,version,payload,message,created_by:actor.id})).error;if(e)throw e;e=(await db.from("content_entities").upsert({entity_type:type,entity_id:id,published:payload,published_version:version,updated_by:actor.id,updated_at:new Date().toISOString()})).error;if(e)throw e;e=(await db.from("content_publications").insert({summary:`${type}:${id} v${version}`,created_by:actor.id})).error;if(e)throw e;await audit(db,{principalId:p?.id,action:"content.publish",targetType:type,targetId:id,before:cur?.published,after:payload});return J({ok:true,id,version})}
  if(r==="/content/rollback"&&req.method==="POST"){const actor=await permission(req,db,"content.rollback"),p=await principalFor(db,actor.id),b=await body(req),type=txt(b.type,64),id=txt(b.id,ID_MAX),version=Number(b.version);if(!Number.isSafeInteger(version)||version<1)throw new AppError(400,"VERSION","Versão inválida.");const {data:v,error:ve}=await db.from("content_versions").select("*").eq("entity_type",type).eq("entity_id",id).eq("version",version).maybeSingle();if(ve)throw ve;if(!v)throw new AppError(404,"VERSION","Versão ausente.");const re=await refs(db,type,v.payload);if(re.length)throw new AppError(409,"ROLLBACK_REFERENCES",re.join(" | "));const {data:cur,error:ce}=await db.from("content_entities").select("*").eq("entity_type",type).eq("entity_id",id).single();if(ce)throw ce;const nv=Number(cur.published_version)+1;let e=(await db.from("content_versions").insert({entity_type:type,entity_id:id,version:nv,payload:v.payload,message:`rollback de v${version}`,created_by:actor.id})).error;if(e)throw e;e=(await db.from("content_entities").update({published:v.payload,published_version:nv,updated_by:actor.id,updated_at:new Date().toISOString()}).eq("entity_type",type).eq("entity_id",id)).error;if(e)throw e;await audit(db,{principalId:p?.id,action:"content.rollback",targetType:type,targetId:id,before:cur.published,after:v.payload});return J({ok:true,version:nv})}
  if(r==="/events"&&req.method==="GET"){await permission(req,db,"events.read");const {data,error}=await db.from("event_instances").select("*").order("starts_at",{ascending:false}).limit(100);if(error)throw error;return J({ok:true,events:data||[]})}
  if(r==="/events"&&req.method==="POST"){const actor=await permission(req,db,"events.write"),p=await principalFor(db,actor.id),b=await body(req),name=txt(b.name,160),cycle=txt(b.cycle,32),start=new Date(String(b.starts_at||"")),end=new Date(String(b.ends_at||""));if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start)throw new AppError(400,"EVENT_WINDOW","Janela do evento inválida.");const mission_ids=Array.isArray(b.mission_ids)?b.mission_ids.map((x:any)=>txt(x,ID_MAX)).slice(0,100):[],modifiers=Array.isArray(b.modifiers)?b.modifiers.slice(0,100):[],reward_budget=Number(b.reward_budget??0);if(!Number.isSafeInteger(reward_budget)||reward_budget<0||reward_budget>1_000_000_000)throw new AppError(400,"REWARD_BUDGET","Reward budget inválido.");const status=String(b.status||"SCHEDULED").toUpperCase();if(!["SCHEDULED","ACTIVE","ENDED","CANCELLED"].includes(status))throw new AppError(400,"EVENT_STATUS","Status inválido.");const payload={template_id:b.template_id?txt(b.template_id,ID_MAX):null,name,cycle,starts_at:start.toISOString(),ends_at:end.toISOString(),boss_id:b.boss_id?txt(b.boss_id,ID_MAX):null,mission_ids,modifiers,reward_budget,announcement:b.announcement?String(b.announcement).slice(0,1000):null,status,created_by:actor.id};const {data,error}=await db.from("event_instances").insert(payload).select("*").single();if(error)throw error;await audit(db,{principalId:p?.id,action:"event.create",targetType:"event",targetId:data.id,after:data});return J({ok:true,event:data})}
  if(r==="/audit"&&req.method==="GET"){await permission(req,db,"audit.read");const {data,error}=await db.from("admin_audit_log").select("*").order("created_at",{ascending:false}).limit(500);if(error)throw error;return J({ok:true,entries:data||[]})}
  return J({ok:false,code:"ROUTE",error:"Rota administrativa desconhecida."},404)
}catch(e:any){if(e instanceof AppError)return J({ok:false,code:e.code,error:e.message},e.status);console.error("admin",e);return J({ok:false,code:"ADMIN_API",error:"Falha interna na administração."},503)}});
